Feature: Verify ETA Fare with Pegasus API

    Everybody wants to connect socket successful

    Scenario: 01. Connect socket Create Account
        Given I request connect socket to "https://dispatcher.lab.qup.vn"
        And I want register socket with data
            | platform | phone                                 | fleetId | appType   | verifyCode | ime                                  | appName   | rv       | password |
            | android  | {"number":"909119999","country":"VN"} | tappcar | passenger | 1211       | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | 4.6.2500 |          |
        When I get my account info "register"
        Then I get return info with passenger info
            | res                                                   |
            | {"info":{"fleetId":"tappcar","phone":"+84909119999"}} |


    Scenario: 02. Login & get User Info
        Given Get token when login Account Pegasus on Server API "https://dispatcher.lab.qup.vn/oauth/app/token"
            | grant_type   | phone                                 | device_token                         | client_id | client_secret |
            | device_token | {"number":"909119999","country":"VN"} | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | qup           |
        Then I get return result after Login Pegasus app
            | res |
            | {}  |


    Scenario: 03. Connect socket Update Profile Account
        Given I request connect socket to "https://dispatcher.lab.qup.vn"
        And I want register socket with data
            | platform | phone                                 | fleetId | appType   | verifyCode | ime                                  | appName   | rv       | password |
            | android  | {"number":"909119999","country":"VN"} | tappcar | passenger | 1211       | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | 4.6.2500 |          |
        When I send a request to edit account profile with "editProfile"
            | firstName | lastName  | email                | tips | gender | dob        | street                   | city       | state | zipcode | country |
            | VIP       | Auto Test | tester.qup@gmail.com | 15   | 2      | 09/29/1999 | 1600 Pennsylvania Ave NW | Washington | DC    | 20500   | Vietnam |
        Then I get return info with passenger info
            | res                                                                                                                                                                                                                                                                                                                                                                                             |
            | {"returnCode":200,"response":{"phone":"+84909119999","firstName":"VIP","lastName":"Auto Test","fullName":"VIP Auto Test","fullNameSort":"vip auto test","email":"tester.qup@gmail.com","firstRegisterFrom":"App","tips":"15","profile":{"gender":2,"dob":"09/29/1999","address":{"street":"1600 Pennsylvania Ave NW","city":"Washington","state":"DC","zipcode":"20500","country":"Vietnam"}}}} |


    Scenario: 04. Pegasus app Login & ETA Fare with Premium cartype
        Given Get token when login Account Pegasus on Server API "https://dispatcher.lab.qup.vn/oauth/app/token"
            | grant_type   | phone                                 | device_token                         | client_id | client_secret |
            | device_token | {"number":"909119999","country":"VN"} | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | qup           |
        When I request API of Pegasus "https://dispatcher.lab.qup.vn/api/v3/eta/eta_fare_multi_cartype" with request with params based on table below
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
            | {"userId": "5b2387f4a72d14173a3f5c08", "bookFrom": "TappCar", "city": "Danang", "corporateId": "", "pickup": [108.217281,16.089731], "destination": [108.3380469,15.8800584], "distance": 4608, "duration": 805, "fleetId": "tappcar", "pickupTime": "Now", "pricingType": 0, "zipCodeFrom": "550000", "zipCodeTo": "550000", "promoCode": "", "meetDriver": -1, "rateDetails": [ { "vehicleTypeId": "Premium", "packageRateId": "", "bookType": 0, "typeRate": 0, "distance": 31000, "duration": 1800, "pickupTime":"Now", "services": [] } ] } |
        Then I get return result after request API of Pegasus app
            | res                                                                                                                                                                                                                                                                                                                                                                                                                                               |
            | {"response":[{"basicFare":302,"etaFare":399.69,"currencyISO":"CAD","airportFee":0,"meetDriverFee":0,"rushHourFee":9.99,"techFee":1.5,"bookingFee":0,"tollFee":0,"tax":25.34,"tip":10.86,"minFare":20,"normalFare":true,"route":"","vehicleType":"Premium","min":false,"otherFees":50,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"typeRate":0,"extraDistanceFee":0,"extraDurationFee":0,"taxValue":0,"tipValue":0}],"returnCode":200} |


# Scenario: 04. Login & ETA Fare with "Bike" & "Xe 4 Chỗ" cartype
#     Given Get token when login Account Pegasus on Server API "https://dispatcher.lab.qup.vn/oauth/app/token"
#         | grant_type   | phone                                 | device_token                         | client_id | client_secret |
#         | device_token | {"number":"909119999","country":"VN"} | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | qup           |
#     When I request API of Pegasus "https://dispatcher.lab.qup.vn/api/v3/eta/eta_fare_multi_cartype" with params based on "booking-requestEta-APIparams.json"
#         | fleetId    | bookFrom | city                     | meetDriver | pricingType | pickupTime       | userId                   | pickup                 | zipCodeTo | destination            | zipCodeFrom | rateDetails                                                                                                                                                                                                                                                                                                     |
#         | tappcar | Pax Plus | 550000__Đà Nẵng_Việt Nam | -1         | 0           | 2018-11-30 15:28 | 5bf3925b13fbf2534fe2b70d | [108.206474,16.058692] | 550000    | [108.244435,16.063404] | 550000      | [{ "vehicleTypeId": "Bike", "packageRateId": "", "typeRate": 0, "distance": 4608, "duration": 805, "pickupTime": "2018-11-30 15:28", "services": [] },{ "vehicleTypeId": "Xe 4 Chỗ", "packageRateId": "", "typeRate": 0, "distance": 4608, "duration": 805, "pickupTime": "2018-11-30 15:28", "services": [] }] |
#     Then I get return result after request API of Pegasus app
#         | res                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
#         | {"response":[{"basicFare":47173.33,"etaFare":120780.66,"currencyISO":"VND","airportFee":0,"meetDriverFee":0,"rushHourFee":9900,"techFee":3000,"bookingFee":0,"tollFee":0,"tax":7495.13,"tip":3212.2,"minFare":20000,"normalFare":true,"route":"","vehicleType":"Bike","min":false,"otherFees":50000,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"typeRate":0,"extraDistanceFee":0,"extraDurationFee":0},{"basicFare":78418.33,"etaFare":155150.16,"currencyISO":"VND","airportFee":0,"meetDriverFee":0,"rushHourFee":9900,"techFee":3000,"bookingFee":0,"tollFee":0,"tax":9682.28,"tip":4149.55,"minFare":30000,"normalFare":true,"route":"","vehicleType":"Xe 4 Chỗ","min":false,"otherFees":50000,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"typeRate":0,"extraDistanceFee":0,"extraDurationFee":0}]} |

# # Khác distance / duration truyền vô
# Scenario: 05. Login & ETA Fare with Bike cartype
#     Given Get token when login Account Pegasus on Server API "https://dispatcher.lab.qup.vn/oauth/app/token"
#         | grant_type   | phone                                 | device_token                         | client_id | client_secret |
#         | device_token | {"number":"909119999","country":"VN"} | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | qup           |
#     When I request API of Pegasus "https://dispatcher.lab.qup.vn/api/v3/eta/eta_fare_multi_cartype" with params based on "booking-requestEta-APIparams.json"
#         | fleetId    | bookFrom | city                     | meetDriver | pricingType | pickupTime | userId                   | pickup                 | zipCodeTo | destination            | zipCodeFrom | rateDetails                                                                                                                                                                                                                                                                            |
#         | tappcar | Pax Plus | 550000__Đà Nẵng_Việt Nam | -1         | 0           | Now        | 5bf3925b13fbf2534fe2b70d | [108.206474,16.058692] | 550000    | [108.244435,16.063404] | 550000      | [{ "vehicleTypeId": "Bike", "packageRateId": "", "typeRate": 0, "distance": 10761, "duration": 805, "pickupTime":"Now", "services": [] }, { "vehicleTypeId": "Xe 4 Chỗ", "packageRateId": "", "typeRate": 0, "distance": 10761, "duration": 805, "pickupTime":"Now", "services": [] }] |
#     Then I get return result after request API of Pegasus app
#         | res                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
#         | {"response":[{"basicFare":92003.33,"etaFare":170093.66,"currencyISO":"VND","airportFee":0,"meetDriverFee":0,"rushHourFee":9900,"techFee":3000,"bookingFee":0,"tollFee":0,"tax":10633.23,"tip":4557.1,"minFare":15000,"normalFare":true,"route":"","vehicleType":"Bike","min":false,"otherFees":50000,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0},{"basicFare":134548.33,"etaFare":216893.16,"currencyISO":"VND","airportFee":0,"meetDriverFee":0,"rushHourFee":9900,"techFee":3000,"bookingFee":0,"tollFee":0,"tax":13611.38,"tip":5833.45,"minFare":150000,"normalFare":true,"route":"","vehicleType":"Xe 4 Chỗ","min":false,"otherFees":50000,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0}],"returnCode":200} |

# Scenario: 06. Login & ETA Fare with "Bike" & "Xe 4 Chỗ" cartype
#     Given Get token when login Account Pegasus on Server API "https://dispatcher.lab.qup.vn/oauth/app/token"
#         | grant_type   | phone                                 | device_token                         | client_id | client_secret |
#         | device_token | {"number":"909119999","country":"VN"} | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | qup           |
#     When I request API of Pegasus "https://dispatcher.lab.qup.vn/api/v3/eta/eta_fare_multi_cartype" with params based on "booking-requestEta-APIparams.json"
#         | fleetId    | bookFrom | city                     | meetDriver | pricingType | pickupTime       | userId                   | pickup                 | zipCodeTo | destination            | zipCodeFrom | rateDetails                                                                                                                                                                                                                                                                                                      |
#         | tappcar | Pax Plus | 550000__Đà Nẵng_Việt Nam | -1         | 0           | 2018-11-30 15:28 | 5bf3925b13fbf2534fe2b70d | [108.206474,16.058692] | 550000    | [108.244435,16.063404] | 550000      | [{ "vehicleTypeId": "Bike", "packageRateId": "", "typeRate": 0, "distance": 10761, "duration": 805, "pickupTime":"2018-11-30 15:28", "services": [] }, { "vehicleTypeId": "Xe 4 Chỗ", "packageRateId": "", "typeRate": 0, "distance": 10761, "duration": 805, "pickupTime":"2018-11-30 15:28", "services": [] }] |
#     Then I get return result after request API of Pegasus app
#         | res                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
#         | {"response":[{ "basicFare": 96003.33, "etaFare": 174493.66, "currencyISO": "VND", "airportFee": 0, "meetDriverFee": 0, "rushHourFee": 9900, "techFee": 3000, "bookingFee": 0, "tollFee": 0, "tax": 10913.23, "tip": 4677.1, "minFare": 20000, "normalFare": true, "route": "", "vehicleType": "Bike", "min": false, "otherFees": 50000, "promoAmount": 0, "bookingFeeActive": false, "serviceFee": 0 },{ "basicFare": 138548.33, "etaFare": 221293.16, "currencyISO": "VND", "airportFee": 0, "meetDriverFee": 0, "rushHourFee": 9900, "techFee": 3000, "bookingFee": 0, "tollFee": 0, "tax": 13891.38, "tip": 5953.45, "minFare": 30000, "normalFare": true, "route": "", "vehicleType": "Xe 4 Chỗ", "min": false, "otherFees": 50000, "promoAmount": 0, "bookingFeeActive": false, "serviceFee": 0 }],"returnCode":200} |

# # ETA Hourly Fare
# Scenario: 07. Login & ETA Hourly Fare with Bike cartype
#     Given Get token when login Account Pegasus on Server API "https://dispatcher.lab.qup.vn/oauth/app/token"
#         | grant_type   | phone                                 | device_token                         | client_id | client_secret |
#         | device_token | {"number":"909119999","country":"VN"} | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | qup           |
#     When I request API of Pegasus "https://dispatcher.lab.qup.vn/api/v3/eta/eta_fare_multi_cartype" with params based on "booking-requestEta-APIparams.json"
#         | fleetId    | bookFrom | city                     | meetDriver | pricingType | pickupTime | userId                   | pickup                 | zipCodeTo | destination            | zipCodeFrom | rateDetails                                                                                                                                                                                                                                                                                           |
#         | tappcar | Pax Plus | 550000__Đà Nẵng_Việt Nam | -1         | 0           | Now        | 5bf3925b13fbf2534fe2b70d | [108.206474,16.058692] | 550000    | [108.244435,16.063404] | 550000      | [{ "vehicleTypeId": "Bike", "packageRateId": "", "bookType": 3, "typeRate": 1, "distance": 10761, "duration": 805, "pickupTime":"Now", "services": [] }, { "vehicleTypeId": "Xe 4 Chỗ", "packageRateId": "", "typeRate": 0, "distance": 10761, "duration": 805, "pickupTime":"Now", "services": [] }] |
#     Then I get return result after request API of Pegasus app
#         | res                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
#         | { "response":[{"basicFare":200000, "etaFare":288890, "currencyISO":"VND", "airportFee":0, "meetDriverFee": 0, "rushHourFee":9900, "techFee":3000, "bookingFee":0, "tollFee":0, "tax":18193, "tip":7797, "minFare":0, "normalFare":false, "route":"", "vehicleType":"Bike", "min":false, "otherFees":50000, "promoAmount":0, "bookingFeeActive": false, "serviceFee": 0, "packages": [ { "duration": 1, "feesByCurrencies": [ { "currencyISO": "VND", "basedFee": 200000, "extraDuration": 180000, "extraDistance":10000 } ], "coveredDistance": 50, "extraDistanceFee": 0, "name": "1 Hour", "extraDurationFee": 0, "_id": "5c010f8e584a0f538f6a20ec", "type": "hour", "value": 288890 }, { "duration": 1, "feesByCurrencies": [ { "currencyISO": "VND", "basedFee": 800000, "extraDuration": 600000, "extraDistance": 10000 } ], "coveredDistance": 500, "extraDistanceFee": 0, "name": "Daily Package 1 Day", "extraDurationFee": 0, "_id": "5c0110b8584a0f538f6a20ee", "type":"day", "value":948890 }], "typeRate":2,"extraDistanceFee":0,"extraDurationFee":0 } ], "returnCode":200 } |

# Scenario: 08. Login & ETA Hourly Reservation Fare with multi cartype (Bike & Xe 4 chỗ)
#     Given Get token when login Account Pegasus on Server API "https://dispatcher.lab.qup.vn/oauth/app/token"
#         | grant_type   | phone                                 | device_token                         | client_id | client_secret |
#         | device_token | {"number":"909119999","country":"VN"} | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | qup           |
#     When I request API of Pegasus "https://dispatcher.lab.qup.vn/api/v3/eta/eta_fare_multi_cartype" with params based on "booking-requestEta-APIparams.json"
#         | fleetId    | bookFrom | city                     | meetDriver | pricingType | pickupTime       | userId                   | pickup                 | zipCodeTo | destination            | zipCodeFrom | rateDetails                                                                                                                                                                                                                                                                                                                                                                                      |
#         | tappcar | Pax Plus | 550000__Đà Nẵng_Việt Nam | -1         | 0           | 2018-12-30 15:28 | 5bf3925b13fbf2534fe2b70d | [108.206474,16.058692] | 550000    | [108.244435,16.063404] | 550000      | [{ "vehicleTypeId": "Bike", "packageRateId": "5c010f8e584a0f538f6a20ec", "bookType": 3, "typeRate": 0, "distance": 10761, "duration": 1236, "pickupTime":"2018-12-30 15:28", "services": [] }, { "vehicleTypeId": "Xe 4 Chỗ", "packageRateId": "5c0113d5584a0f538f6a20f3", "bookType": 3, "typeRate": 0, "distance": 10761, "duration": 1236, "pickupTime":"2018-12-30 15:28", "services": [] }] |
#     Then I get return result after request API of Pegasus app
#         | res                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
#         | { "response":[{ "basicFare":200000, "etaFare":288890, "currencyISO":"VND", "airportFee":0, "meetDriverFee":0, "rushHourFee":9900, "techFee": 3000, "bookingFee": 0, "tollFee": 0, "tax": 18193, "tip": 7797, "minFare": 0, "normalFare": false, "route": "", "vehicleType": "Bike", "min": false, "otherFees": 50000, "promoAmount": 0, "bookingFeeActive": false, "serviceFee": 0, "packages": [ { "duration": 1, "feesByCurrencies": [ { "currencyISO": "VND", "basedFee": 200000, "extraDuration": 180000, "extraDistance": 10000 } ], "coveredDistance": 50, "extraDistanceFee": 0, "name": "1 Hour", "extraDurationFee": 0, "_id": "5c010f8e584a0f538f6a20ec", "type": "hour", "value": 288890 }, { "duration": 1, "feesByCurrencies": [ { "currencyISO": "VND", "basedFee": 800000, "extraDuration": 600000, "extraDistance": 10000 } ], "coveredDistance": 500, "extraDistanceFee": 0, "name": "Daily Package 1 Day", "extraDurationFee": 0, "_id": "5c0110b8584a0f538f6a20ee", "type": "day", "value": 948890 }],"typeRate":2,"extraDistanceFee":0,"extraDurationFee":0}, { "basicFare": 900000, "etaFare": 1058890, "currencyISO": "VND", "airportFee": 0, "meetDriverFee": 0, "rushHourFee": 9900, "techFee": 3000, "bookingFee": 0, "tollFee": 0, "tax": 67193, "tip": 28797, "minFare": 0, "normalFare": false, "route": "", "vehicleType": "Xe 4 Chỗ", "min": false, "otherFees": 50000, "promoAmount": 0, "bookingFeeActive": false, "serviceFee": 0, "packages": [ { "duration": 1, "feesByCurrencies": [ { "currencyISO": "VND", "basedFee": 900000, "extraDuration": 800000, "extraDistance": 20000 } ], "coveredDistance": 600, "extraDistanceFee": 0, "name": "Daily Car", "extraDurationFee": 0, "_id": "5c0113d5584a0f538f6a20f3", "type": "day", "value": 1058890 } ],"typeRate":2,"extraDistanceFee":0,"extraDurationFee":0 } ], "returnCode": 200 } |

# # ETA Flat Fare
# Scenario: 09. Login & ETA Flat Fare booking & type Now with many cartype
#     Given Get token when login Account Pegasus on Server API "https://dispatcher.lab.qup.vn/oauth/app/token"
#         | grant_type   | phone                                 | device_token                         | client_id | client_secret |
#         | device_token | {"number":"909119999","country":"VN"} | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | qup           |
#     When I request API of Pegasus "https://dispatcher.lab.qup.vn/api/v3/eta/eta_fare_multi_cartype" with params based on "booking-requestEta-APIparams.json"
#         | fleetId    | bookFrom | city                     | meetDriver | pricingType | pickupTime | userId                   | pickup                 | zipCodeTo | destination            | zipCodeFrom | rateDetails                                                                                                                                                                                                                                                                            |
#         | tappcar | Pax Plus | 550000__Đà Nẵng_Việt Nam | -1         | 0           | Now        | 5bf3925b13fbf2534fe2b70d | [108.219906,16.085142] | 550000    | [108.263725,16.013376] | 550000      | [{ "vehicleTypeId": "Bike", "packageRateId": "", "typeRate": 0, "distance": 10761, "duration": 805, "pickupTime":"Now", "services": [] }, { "vehicleTypeId": "Xe 4 Chỗ", "packageRateId": "", "typeRate": 0, "distance": 10761, "duration": 805, "pickupTime":"Now", "services": [] }] |
#     Then I get return result after request API of Pegasus app
#         | res                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
#         | { "response": [ { "basicFare": 100000, "etaFare": 178890, "currencyISO": "VND", "airportFee": 0, "meetDriverFee": 0, "rushHourFee": 9900, "techFee": 3000, "bookingFee": 0, "tollFee": 0, "tax": 11193, "tip": 4797, "minFare": 0, "normalFare": false, "route": "Auto Test Flat", "vehicleType": "Bike", "min": false, "otherFees": 50000, "promoAmount": 0, "bookingFeeActive": false, "serviceFee": 0,"typeRate":1,"extraDistanceFee":0,"extraDurationFee":0 }, { "basicFare": 134548.33, "etaFare": 216893.16, "currencyISO": "VND", "airportFee": 0, "meetDriverFee": 0, "rushHourFee": 9900, "techFee": 3000, "bookingFee": 0, "tollFee": 0, "tax": 13611.38, "tip": 5833.45, "minFare": 150000, "normalFare": true, "route": "", "vehicleType": "Xe 4 Chỗ", "min": false, "otherFees": 50000, "promoAmount": 0, "bookingFeeActive": false, "serviceFee": 0,"typeRate":0,"extraDistanceFee":0,"extraDurationFee":0 } ], "returnCode": 200 } |


# Scenario: 10. Login & ETA Flat Fare booking & type Reservation (none time) with many cartype
#     Given Get token when login Account Pegasus on Server API "https://dispatcher.lab.qup.vn/oauth/app/token"
#         | grant_type   | phone                                 | device_token                         | client_id | client_secret |
#         | device_token | {"number":"909119999","country":"VN"} | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | qup           |
#     When I request API of Pegasus "https://dispatcher.lab.qup.vn/api/v3/eta/eta_fare_multi_cartype" with params based on "booking-requestEta-APIparams.json"
#         | fleetId    | bookFrom | city                     | meetDriver | pricingType | pickupTime  | userId                   | pickup                 | zipCodeTo | destination            | zipCodeFrom | rateDetails                                                                                                                                                                                                                                                                                            |
#         | tappcar | Pax Plus | 550000__Đà Nẵng_Việt Nam | -1         | 0           | Reservation | 5bf3925b13fbf2534fe2b70d | [108.219906,16.085142] | 550000    | [108.263725,16.013376] | 550000      | [{ "vehicleTypeId": "Bike", "packageRateId": "", "typeRate": 0, "distance": 10761, "duration": 805, "pickupTime":"Reservation", "services": [] }, { "vehicleTypeId": "Xe 4 Chỗ", "packageRateId": "", "typeRate": 0, "distance": 10761, "duration": 805, "pickupTime":"Reservation", "services": [] }] |
#     Then I get return result after request API of Pegasus app
#         | res                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
#         | { "response":[{ "basicFare": 100000, "etaFare": 168000, "currencyISO": "VND", "airportFee": 0, "meetDriverFee": 0, "rushHourFee": 0, "techFee": 3000, "bookingFee": 0, "tollFee": 0, "tax": 10500, "tip": 4500, "minFare": 0, "normalFare": false, "route": "Auto Test Flat", "vehicleType": "Bike", "min": false, "otherFees": 50000, "promoAmount": 0, "bookingFeeActive": false, "serviceFee": 0,"typeRate":1,"extraDistanceFee":0,"extraDurationFee":0 }, { "basicFare": 138548.33, "etaFare": 210403.16, "currencyISO": "VND", "airportFee": 0, "meetDriverFee": 0, "rushHourFee": 0, "techFee": 3000, "bookingFee": 0, "tollFee": 0, "tax": 13198.38, "tip": 5656.45, "minFare": 30000, "normalFare": true, "route": "", "vehicleType": "Xe 4 Chỗ", "min": false, "otherFees": 50000, "promoAmount": 0, "bookingFeeActive": false, "serviceFee": 0,"typeRate":0,"extraDistanceFee":0,"extraDurationFee":0 } ], "returnCode": 200 } |
