Feature: Verify ETA Fare with Pegasus API

    I wants to eta correctly
    I check pickup is now and reservation have pickupTime is 2018-12-30 15:28

    Scenario: 01. Connect socket Create Account
        Given I request connect socket to "https://dispatcher.lab.qup.vn"
        And I want register socket with data
            | platform | phone                                 | fleetId | appType   | verifyCode | ime                                  | appName   | rv       | password |
            | android  | {"number":"909119999","country":"VN"} | tappcar | passenger | 1211       | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | 4.6.2500 |          |
        When I get my account info "register"
        Then I get return info with passenger info
            | res                                                   |
            | {"info":{"fleetId":"tappcar","phone":"+84909119999"}} |


    Scenario: 02. Login & get User Info
        Given Get token when login Account Pegasus on Server API "https://dispatcher.lab.qup.vn/oauth/app/token"
            | grant_type   | phone                                 | device_token                         | client_id | client_secret            |
            | device_token | {"number":"909119999","country":"VN"} | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | 59b0a8bb91b10a2a7a44e5e1 |
        Then I get return result after Login Pegasus app
            | res |
            | {}  |


    Scenario: 03. Connect socket Update Profile Account
        Given I request connect socket to "https://dispatcher.lab.qup.vn"
        And I want register socket with data
            | platform | phone                                 | fleetId | appType   | verifyCode | ime                                  | appName   | rv       | password |
            | android  | {"number":"909119999","country":"VN"} | tappcar | passenger | 1211       | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | 4.6.2500 |          |
        When I send a request to edit account profile with "editProfile"
            | firstName | lastName  | email                | tips | gender | dob        | street                   | city       | state | zipcode | country |
            | VIP       | Auto Test | tester.qup@gmail.com | 0    | 2      | 09/29/1999 | 1600 Pennsylvania Ave NW | Washington | DC    | 20500   | Vietnam |
        Then I get return info with passenger info
            | res                                                                                                                                                                                                                                                                                                                                                                                            |
            | {"returnCode":200,"response":{"phone":"+84909119999","firstName":"VIP","lastName":"Auto Test","fullName":"VIP Auto Test","fullNameSort":"vip auto test","email":"tester.qup@gmail.com","firstRegisterFrom":"App","tips":"0","profile":{"gender":2,"dob":"09/29/1999","address":{"street":"1600 Pennsylvania Ave NW","city":"Washington","state":"DC","zipcode":"20500","country":"Vietnam"}}}} |


    Scenario: 04. Pegasus app Login & ETA Fare with "Premium" cartype
        Given Get token when login Account Pegasus on Server API "https://dispatcher.lab.qup.vn/oauth/app/token"
            | grant_type   | phone                                 | device_token                         | client_id | client_secret            |
            | device_token | {"number":"909119999","country":"VN"} | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | 59b0a8bb91b10a2a7a44e5e1 |
        When I request API of Pegasus "https://dispatcher.lab.qup.vn/api/v3/eta/eta_fare_multi_cartype" with request with params based on table below
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
            | {"userId": "5b2387f4a72d14173a3f5c08", "bookFrom": "TappCar", "city": "Danang", "corporateId": "", "pickup": [108.217281,16.089731], "destination": [108.3380469,15.8800584], "distance": 4608, "duration": 805, "fleetId": "tappcar", "pickupTime": "Now", "pricingType": 0, "zipCodeFrom": "550000", "zipCodeTo": "550000", "promoCode": "", "meetDriver": -1, "rateDetails": [ { "vehicleTypeId": "Premium", "packageRateId": "", "bookType": 0, "typeRate": 0, "distance": 31000, "duration": 1800, "pickupTime":"Now", "services": [] } ] } |
        Then I get return result after request API of Pegasus app
            | res                                                                                                                                                                                                                                                                                                                                                                                                                                               |
            | {"response":[{"basicFare":302,"etaFare":399.69,"currencyISO":"CAD","airportFee":0,"meetDriverFee":0,"rushHourFee":9.99,"techFee":1.5,"bookingFee":0,"tollFee":0,"tax":25.34,"tip":10.86,"minFare":20,"normalFare":true,"route":"","vehicleType":"Premium","min":false,"otherFees":50,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"typeRate":0,"extraDistanceFee":0,"extraDurationFee":0,"taxValue":0,"tipValue":0}],"returnCode":200} |


    Scenario: 05. Login & ETA Fare with "Premium" & "SUV" cartype
        Given Get token when login Account Pegasus on Server API "https://dispatcher.lab.qup.vn/oauth/app/token"
            | grant_type   | phone                                 | device_token                         | client_id | client_secret            |
            | device_token | {"number":"909119999","country":"VN"} | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | 59b0a8bb91b10a2a7a44e5e1 |
        When I request API of Pegasus "https://dispatcher.lab.qup.vn/api/v3/eta/eta_fare_multi_cartype" with request with params based on table below
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
            | {"userId": "5b2387f4a72d14173a3f5c08", "bookFrom": "TappCar", "city": "Danang", "corporateId": "", "pickup": [108.217281,16.089731], "destination": [108.3380469,15.8800584], "distance": 4608, "duration": 805, "fleetId": "tappcar", "pickupTime": "Now", "pricingType": 0, "zipCodeFrom": "550000", "zipCodeTo": "550000", "promoCode": "", "meetDriver": -1, "rateDetails": [ { "vehicleTypeId": "Premium", "packageRateId": "", "bookType": 0, "typeRate": 0, "distance": 31000, "duration": 1800, "pickupTime":"Now", "services": [] }, { "vehicleTypeId": "SUV", "packageRateId": "", "bookType": 0, "typeRate": 0, "distance": 31000, "duration": 1800, "pickupTime":"Now", "services": [] } ] } |
        Then I get return result after request API of Pegasus app
            | res                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
            | {"response":[{"basicFare":302,"etaFare":399.69,"currencyISO":"CAD","airportFee":0,"meetDriverFee":0,"rushHourFee":9.99,"techFee":1.5,"bookingFee":0,"tollFee":0,"tax":25.34,"tip":10.86,"minFare":20,"normalFare":true,"route":"","vehicleType":"Premium","min":false,"otherFees":50,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"typeRate":0,"extraDistanceFee":0,"extraDurationFee":0,"taxValue":0,"tipValue":0},{"basicFare":364,"etaFare":467.89,"currencyISO":"CAD","airportFee":0,"meetDriverFee":0,"rushHourFee":9.99,"techFee":1.5,"bookingFee":0,"tollFee":0,"tax":29.68,"tip":12.72,"minFare":30,"normalFare":true,"route":"","vehicleType":"SUV","min":false,"otherFees":50,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"typeRate":0,"extraDistanceFee":0,"extraDurationFee":0,"taxValue":0,"tipValue":0}],"returnCode":200} |


    # Khác distance / duration truyền vô
    Scenario: 06. Login & ETA Fare with Premium" & "SUV" cartype have "pickupTime" is Now
        Given Get token when login Account Pegasus on Server API "https://dispatcher.lab.qup.vn/oauth/app/token"
            | grant_type   | phone                                 | device_token                         | client_id | client_secret            |
            | device_token | {"number":"909119999","country":"VN"} | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | 59b0a8bb91b10a2a7a44e5e1 |
        When I request API of Pegasus "https://dispatcher.lab.qup.vn/api/v3/eta/eta_fare_multi_cartype" with request with params based on table below
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
            | {"userId": "5b2387f4a72d14173a3f5c08", "bookFrom": "TappCar", "city": "Danang", "corporateId": "", "pickup": [108.206474,16.058692], "destination": [108.244435,16.063404], "distance": 4608, "duration": 805, "fleetId": "tappcar", "pickupTime": "Now", "pricingType": 0, "zipCodeFrom": "550000", "zipCodeTo": "550000", "promoCode": "", "meetDriver": -1, "rateDetails": [ { "vehicleTypeId": "Premium", "packageRateId": "", "bookType": 0, "typeRate": 0, "distance": 10761, "duration": 805, "pickupTime":"Now", "services": [] }, { "vehicleTypeId": "SUV", "packageRateId": "", "bookType": 0, "typeRate": 0, "distance": 10761, "duration": 805, "pickupTime":"Now", "services": [] } ] } |
        Then I get return result after request API of Pegasus app
            | res                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
            | {"response":[{"basicFare":135.11,"etaFare":216.11,"currencyISO":"CAD","airportFee":0,"meetDriverFee":0,"rushHourFee":9.99,"techFee":1.5,"bookingFee":0,"tollFee":0,"tax":13.66,"tip":5.85,"minFare":20,"normalFare":true,"route":"","vehicleType":"Premium","min":false,"otherFees":50,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"typeRate":0,"extraDistanceFee":0,"extraDurationFee":0,"taxValue":0,"tipValue":0},{"basicFare":154.83,"etaFare":237.8,"currencyISO":"CAD","airportFee":0,"meetDriverFee":0,"rushHourFee":9.99,"techFee":1.5,"bookingFee":0,"tollFee":0,"tax":15.04,"tip":6.44,"minFare":30,"normalFare":true,"route":"","vehicleType":"SUV","min":false,"otherFees":50,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"typeRate":0,"extraDistanceFee":0,"extraDurationFee":0,"taxValue":0,"tipValue":0}],"returnCode":200} |


    Scenario: 07. Login & ETA Fare with "Premium" & "SUV" cartype have "pickupTime" is "2018-12-30 15:28"
        Given Get token when login Account Pegasus on Server API "https://dispatcher.lab.qup.vn/oauth/app/token"
            | grant_type   | phone                                 | device_token                         | client_id | client_secret            |
            | device_token | {"number":"909119999","country":"VN"} | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | 59b0a8bb91b10a2a7a44e5e1 |
        When I request API of Pegasus "https://dispatcher.lab.qup.vn/api/v3/eta/eta_fare_multi_cartype" with request with params based on table below
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
            | {"userId": "5b2387f4a72d14173a3f5c08", "bookFrom": "TappCar", "city": "Danang", "corporateId": "", "pickup": [108.206474,16.058692], "destination": [108.244435,16.063404], "distance": 4608, "duration": 805, "fleetId": "tappcar", "pickupTime": "2018-12-30 15:28", "pricingType": 0, "zipCodeFrom": "550000", "zipCodeTo": "550000", "promoCode": "", "meetDriver": -1, "rateDetails": [ { "vehicleTypeId": "Premium", "packageRateId": "", "bookType": 0, "typeRate": 0, "distance": 10761, "duration": 805, "pickupTime":"2018-12-30 15:28", "services": [] }, { "vehicleTypeId": "SUV", "packageRateId": "", "bookType": 0, "typeRate": 0, "distance": 10761, "duration": 805, "pickupTime":"2018-12-30 15:28", "services": [] } ] } |
        Then I get return result after request API of Pegasus app
            | res                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
            | {"response":[{"basicFare":140.11,"etaFare":221.61,"currencyISO":"CAD","airportFee":0,"meetDriverFee":0,"rushHourFee":9.99,"techFee":1.5,"bookingFee":0,"tollFee":0,"tax":14.01,"tip":6,"minFare":25,"normalFare":true,"route":"","vehicleType":"Premium","min":false,"otherFees":50,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"typeRate":0,"extraDistanceFee":0,"extraDurationFee":0,"taxValue":0,"tipValue":0},{"basicFare":160.83,"etaFare":244.4,"currencyISO":"CAD","airportFee":0,"meetDriverFee":0,"rushHourFee":9.99,"techFee":1.5,"bookingFee":0,"tollFee":0,"tax":15.46,"tip":6.62,"minFare":100,"normalFare":true,"route":"","vehicleType":"SUV","min":false,"otherFees":50,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"typeRate":0,"extraDistanceFee":0,"extraDurationFee":0,"taxValue":0,"tipValue":0}],"returnCode":200} |

    # ETA Hourly Fare
    Scenario: 08. Login & ETA Hourly Fare with "Premium" cartype
        Given Get token when login Account Pegasus on Server API "https://dispatcher.lab.qup.vn/oauth/app/token"
            | grant_type   | phone                                 | device_token                         | client_id | client_secret            |
            | device_token | {"number":"909119999","country":"VN"} | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | 59b0a8bb91b10a2a7a44e5e1 |
        When I request API of Pegasus "https://dispatcher.lab.qup.vn/api/v3/eta/eta_fare_multi_cartype" with request with params based on table below
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
            | {"userId": "5b2387f4a72d14173a3f5c08", "bookFrom": "TappCar", "city": "Danang", "corporateId": "", "pickup": [108.206474,16.058692], "destination": [108.244435,16.063404], "distance": 4608, "duration": 805, "fleetId": "tappcar", "pickupTime": "Now", "pricingType": 0, "zipCodeFrom": "550000", "zipCodeTo": "550000", "promoCode": "", "meetDriver": -1, "rateDetails": [ { "vehicleTypeId": "Premium", "packageRateId": "", "bookType": 3, "typeRate": 0, "distance": 10761, "duration": 805, "pickupTime":"Now", "services": [] }] } |
        Then I get return result after request API of Pegasus app
            | res                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
            | {"response":[{"basicFare":100,"etaFare":177.49,"currencyISO":"CAD","airportFee":0,"meetDriverFee":0,"rushHourFee":9.99,"techFee":1.5,"bookingFee":0,"tollFee":0,"tax":11.2,"tip":4.8,"minFare":0,"normalFare":false,"route":"","vehicleType":"Premium","min":false,"otherFees":50,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"packages":[{"duration":1,"feesByCurrencies":[{"currencyISO":"CAD","basedFee":100,"extraDuration":80,"extraDistance":8}],"coveredDistance":9999,"extraDistanceFee":0,"name":"Premium: 1 Hour","extraDurationFee":0,"_id":"58f81478e4b0e611751d03ef","type":"hour","value":177.49},{"duration":1,"feesByCurrencies":[{"currencyISO":"CAD","basedFee":899,"extraDuration":799,"extraDistance":14.99}],"coveredDistance":500,"extraDistanceFee":0,"name":"Premium: 1 Day","extraDurationFee":0,"_id":"5c0f450aaa612f2599146ed2","type":"day","value":1056.39}],"typeRate":2,"extraDistanceFee":0,"extraDurationFee":0,"taxValue":0,"tipValue":0}],"returnCode":200} |


    Scenario: 09. Login & ETA Hourly Fare with "Premium" cartype & package is "Premium: 1 Day"
        Given Get token when login Account Pegasus on Server API "https://dispatcher.lab.qup.vn/oauth/app/token"
            | grant_type   | phone                                 | device_token                         | client_id | client_secret            |
            | device_token | {"number":"909119999","country":"VN"} | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | 59b0a8bb91b10a2a7a44e5e1 |
        When I request API of Pegasus "https://dispatcher.lab.qup.vn/api/v3/eta/eta_fare_multi_cartype" with request with params based on table below
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
            | {"userId": "5b2387f4a72d14173a3f5c08", "bookFrom": "TappCar", "city": "Danang", "corporateId": "", "pickup": [108.206474,16.058692], "destination": [108.244435,16.063404], "distance": 4608, "duration": 805, "fleetId": "tappcar", "pickupTime": "Now", "pricingType": 0, "zipCodeFrom": "550000", "zipCodeTo": "550000", "promoCode": "", "meetDriver": -1, "rateDetails": [ { "vehicleTypeId": "Premium", "packageRateId": "5c0f450aaa612f2599146ed2", "bookType": 3, "typeRate": 0, "distance": 10761, "duration": 805, "pickupTime":"Now", "services": [] }] } |
        Then I get return result after request API of Pegasus app
            | res                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
            | {"response":[{"basicFare":899,"etaFare":1056.39,"currencyISO":"CAD","airportFee":0,"meetDriverFee":0,"rushHourFee":9.99,"techFee":1.5,"bookingFee":0,"tollFee":0,"tax":67.13,"tip":28.77,"minFare":0,"normalFare":false,"route":"","vehicleType":"Premium","min":false,"otherFees":50,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"packages":[{"duration":1,"feesByCurrencies":[{"currencyISO":"CAD","basedFee":100,"extraDuration":80,"extraDistance":8}],"coveredDistance":9999,"extraDistanceFee":0,"name":"Premium: 1 Hour","extraDurationFee":0,"_id":"58f81478e4b0e611751d03ef","type":"hour","value":177.49},{"duration":1,"feesByCurrencies":[{"currencyISO":"CAD","basedFee":899,"extraDuration":799,"extraDistance":14.99}],"coveredDistance":500,"extraDistanceFee":0,"name":"Premium: 1 Day","extraDurationFee":0,"_id":"5c0f450aaa612f2599146ed2","type":"day","value":1056.39}],"typeRate":2,"extraDistanceFee":0,"extraDurationFee":0,"taxValue":0,"tipValue":0}],"returnCode":200} |


    Scenario: 10. Login & ETA Hourly Reservation Fare with multi cartype ("Premium" & "SUV")
        Given Get token when login Account Pegasus on Server API "https://dispatcher.lab.qup.vn/oauth/app/token"
            | grant_type   | phone                                 | device_token                         | client_id | client_secret            |
            | device_token | {"number":"909119999","country":"VN"} | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | 59b0a8bb91b10a2a7a44e5e1 |
        When I request API of Pegasus "https://dispatcher.lab.qup.vn/api/v3/eta/eta_fare_multi_cartype" with request with params based on table below
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
            | {"userId": "5b2387f4a72d14173a3f5c08", "bookFrom": "TappCar", "city": "Danang", "corporateId": "", "pickup": [108.206474,16.058692], "destination": [108.244435,16.063404], "distance": 4608, "duration": 805, "fleetId": "tappcar", "pickupTime": "Now", "pricingType": 0, "zipCodeFrom": "550000", "zipCodeTo": "550000", "promoCode": "", "meetDriver": -1, "rateDetails": [ { "vehicleTypeId": "Premium", "packageRateId": "", "bookType": 3, "typeRate": 0, "distance": 10761, "duration": 805, "pickupTime":"Now", "services": [] }, { "vehicleTypeId": "SUV", "packageRateId": "", "bookType": 3, "typeRate": 0, "distance": 10761, "duration": 805, "pickupTime":"Now", "services": [] } ] } |
        Then I get return result after request API of Pegasus app
            | res                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
            | {"response":[{"basicFare":100,"etaFare":177.49,"currencyISO":"CAD","airportFee":0,"meetDriverFee":0,"rushHourFee":9.99,"techFee":1.5,"bookingFee":0,"tollFee":0,"tax":11.2,"tip":4.8,"minFare":0,"normalFare":false,"route":"","vehicleType":"Premium","min":false,"otherFees":50,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"packages":[{"duration":1,"feesByCurrencies":[{"currencyISO":"CAD","basedFee":100,"extraDuration":80,"extraDistance":8}],"coveredDistance":9999,"extraDistanceFee":0,"name":"Premium: 1 Hour","extraDurationFee":0,"_id":"58f81478e4b0e611751d03ef","type":"hour","value":177.49},{"duration":1,"feesByCurrencies":[{"currencyISO":"CAD","basedFee":899,"extraDuration":799,"extraDistance":14.99}],"coveredDistance":500,"extraDistanceFee":0,"name":"Premium: 1 Day","extraDurationFee":0,"_id":"5c0f450aaa612f2599146ed2","type":"day","value":1056.39}],"typeRate":2,"extraDistanceFee":0,"extraDurationFee":0,"taxValue":0,"tipValue":0},{"basicFare":154.83,"etaFare":237.8,"currencyISO":"CAD","airportFee":0,"meetDriverFee":0,"rushHourFee":9.99,"techFee":1.5,"bookingFee":0,"tollFee":0,"tax":15.04,"tip":6.44,"minFare":30,"normalFare":true,"route":"","vehicleType":"SUV","min":false,"otherFees":50,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"typeRate":0,"extraDistanceFee":0,"extraDurationFee":0,"taxValue":0,"tipValue":0}],"returnCode":200} |


    # ETA Flat Fare
    Scenario: 11. Login & ETA Flat Fare booking & type Now with many cartype
        Given Get token when login Account Pegasus on Server API "https://dispatcher.lab.qup.vn/oauth/app/token"
            | grant_type   | phone                                 | device_token                         | client_id | client_secret            |
            | device_token | {"number":"909119999","country":"VN"} | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | 59b0a8bb91b10a2a7a44e5e1 |
        When I request API of Pegasus "https://dispatcher.lab.qup.vn/api/v3/eta/eta_fare_multi_cartype" with request with params based on table below
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
            | {"userId": "5b2387f4a72d14173a3f5c08", "bookFrom": "TappCar", "city": "Danang", "corporateId": "", "pickup": [108.219906,16.085142], "destination": [108.263725,16.013376], "distance": 20000, "duration": 1500, "fleetId": "tappcar", "pickupTime": "Now", "pricingType": 0, "zipCodeFrom": "550000", "zipCodeTo": "550000", "promoCode": "", "meetDriver": -1, "rateDetails": [ { "vehicleTypeId": "Premium", "packageRateId": "", "bookType": 0, "typeRate": 0, "distance": 20000, "duration": 1500, "pickupTime":"Now", "services": [] }, { "vehicleTypeId": "SUV", "packageRateId": "", "bookType": 0, "typeRate": 0, "distance": 20000, "duration": 1500, "pickupTime":"Now", "services": [] } ] } |
        Then I get return result after request API of Pegasus app
            | res                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
            | {"response":[{"basicFare":19.99,"etaFare":89.48,"currencyISO":"CAD","airportFee":0,"meetDriverFee":0,"rushHourFee":9.99,"techFee":1.5,"bookingFee":0,"tollFee":0,"tax":5.6,"tip":2.4,"minFare":0,"normalFare":false,"route":"3/2 - Hyatt","vehicleType":"Premium","min":false,"otherFees":50,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"typeRate":1,"extraDistanceFee":0,"extraDurationFee":0,"taxValue":0,"tipValue":0},{"basicFare":252.6,"etaFare":345.35,"currencyISO":"CAD","airportFee":0,"meetDriverFee":0,"rushHourFee":9.99,"techFee":1.5,"bookingFee":0,"tollFee":0,"tax":21.88,"tip":9.38,"minFare":30,"normalFare":true,"route":"","vehicleType":"SUV","min":false,"otherFees":50,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"typeRate":0,"extraDistanceFee":0,"extraDurationFee":0,"taxValue":0,"tipValue":0}],"returnCode":200} |


    Scenario: 12. Login & ETA Flat Fare booking & type Reservation (none time) with many cartype
        Given Get token when login Account Pegasus on Server API "https://dispatcher.lab.qup.vn/oauth/app/token"
            | grant_type   | phone                                 | device_token                         | client_id | client_secret            |
            | device_token | {"number":"909119999","country":"VN"} | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | 59b0a8bb91b10a2a7a44e5e1 |
        When I request API of Pegasus "https://dispatcher.lab.qup.vn/api/v3/eta/eta_fare_multi_cartype" with request with params based on table below
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
            | {"userId": "5b2387f4a72d14173a3f5c08", "bookFrom": "TappCar", "city": "Danang", "corporateId": "", "pickup": [108.219906,16.085142], "destination": [108.263725,16.013376], "distance": 20000, "duration": 1500, "fleetId": "tappcar", "pickupTime": "Reservation", "pricingType": 0, "zipCodeFrom": "550000", "zipCodeTo": "550000", "promoCode": "", "meetDriver": -1, "rateDetails": [ { "vehicleTypeId": "Premium", "packageRateId": "", "bookType": 0, "typeRate": 0, "distance": 20000, "duration": 1500, "pickupTime":"Reservation", "services": [] }, { "vehicleTypeId": "SUV", "packageRateId": "", "bookType": 0, "typeRate": 0, "distance": 20000, "duration": 1500, "pickupTime":"Reservation", "services": [] } ] } |
        Then I get return result after request API of Pegasus app
            | res                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
            | {"response":[{"basicFare":19.99,"etaFare":78.49,"currencyISO":"CAD","airportFee":0,"meetDriverFee":0,"rushHourFee":0,"techFee":1.5,"bookingFee":0,"tollFee":0,"tax":4.9,"tip":2.1,"minFare":0,"normalFare":false,"route":"3/2 - Hyatt","vehicleType":"Premium","min":false,"otherFees":50,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"typeRate":1,"extraDistanceFee":0,"extraDurationFee":0,"taxValue":0,"tipValue":0},{"basicFare":258.6,"etaFare":340.96,"currencyISO":"CAD","airportFee":0,"meetDriverFee":0,"rushHourFee":0,"techFee":1.5,"bookingFee":0,"tollFee":0,"tax":21.6,"tip":9.26,"minFare":100,"normalFare":true,"route":"","vehicleType":"SUV","min":false,"otherFees":50,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"typeRate":0,"extraDistanceFee":0,"extraDurationFee":0,"taxValue":0,"tipValue":0}],"returnCode":200} |


    # ####################### Passenger Old #############################


    Scenario: 13. Connect socket Create Account
        Given I request connect socket to "https://dispatcher.lab.qup.vn"
        And I want register socket with data
            | platform | phone                                 | fleetId | appType   | verifyCode | ime                                  | appName   | rv       | password |
            | android  | {"number":"909111222","country":"VN"} | tappcar | passenger | 1211       | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | 4.6.2800 |          |
        When I get my account info "register"
        Then I get return info with passenger info
            | res                                                   |
            | {"info":{"fleetId":"tappcar","phone":"+84909111222"}} |


    Scenario: 14. Connect socket Update Profile Account
        Given I request connect socket to "https://dispatcher.lab.qup.vn"
        And I want register socket with data
            | platform | phone                                 | fleetId | appType   | verifyCode | ime                                  | appName   | rv       | password |
            | android  | {"number":"909111222","country":"VN"} | tappcar | passenger | 1211       | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | 4.6.2800 |          |
        When I send a request to edit account profile with "editProfile"
            | firstName | lastName | email                | tips | gender | dob        | street                   | city       | state | zipcode | country |
            | ABC       | XYZ      | tester.qup@gmail.com | 99   | 2      | 09/29/1999 | 1600 Pennsylvania Ave NW | Washington | DC    | 20500   | Vietnam |
        Then I get return info with passenger info
            | res                                                                                                                                                                                                                                                     |
            | {"returnCode":200,"response":{"phone":"+84909111222","firstName":"ABC","lastName":"XYZ","fullName":"ABC XYZ","fullNameSort":"abc xyz","email":"tester.qup@gmail.com","firstRegisterFrom":"App","tips":"99","avatar":"images/avatar/avatarDefault.png"}} |


    #Pickup location without zone
    Scenario: 15. Connect socket & get Customer Info
        Given I request connect socket to "https://dispatcher.lab.qup.vn"
        And I want register socket with data
            | platform | phone                                 | fleetId | appType   | verifyCode | ime                                  | appName   | rv       | password |
            | android  | {"number":"909111222","country":"VN"} | tappcar | passenger | 1211       | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | 4.6.2800 |          |
        When I send a request to estimate fare with params based on table below
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                            |
            | { "bookFrom": "TappCar", "city": "550000__Đà Nẵng_Việt Nam", "meetDriver": -1, "bookType": 0, "pickupTime": "Now", "zipCodeTo": "550000", "zipCodeFrom": "550000", "fleetId": "tappcar", "userId": "5c0f6dc79eb4565ec59f9342", "vehicleTypeId": "Premium", "distance": 20000, "duration": 1500, "pricingType": 0, "typeRate": 0, "pickup": [ 108.020959,16.280770 ], "destination": [ 108.2119134, 16.0486164 ], "packageRateId": "", "services": [] } |
        Then I get return info with passenger info
            | res                                                                                                                                                                                                                                                                                                                                                                 |
            | {"response":{"basicFare":0,"etaFare":0,"airportFee":0,"meetDriverFee":0,"rushHourFee":0,"techFee":0,"bookingFee":0,"tollFee":0,"tax":0,"tip":0,"minFare":0,"normalFare":false,"min":false,"otherFees":0,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"typeRate":0,"extraDistanceFee":0,"extraDurationFee":0,"taxValue":0,"tipValue":0},"returnCode":306} |


    #Pickup location in zone & regular rate
    Scenario: 16. Connect socket & get eta fare
        Given I request connect socket to "https://dispatcher.lab.qup.vn"
        And I want register socket with data
            | platform | phone                                 | fleetId | appType   | verifyCode | ime                                  | appName   | rv       | password |
            | android  | {"number":"909111222","country":"VN"} | tappcar | passenger | 1211       | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | 4.6.2800 |          |
        When I send a request to estimate fare with params based on table below
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
            | { "bookFrom": "TappCar", "city": "550000__Đà Nẵng_Việt Nam", "meetDriver": -1, "bookType": 0, "pickupTime": "Now", "zipCodeTo": "550000", "zipCodeFrom": "550000", "fleetId": "tappcar", "userId": "5c0f6dc79eb4565ec59f9342", "vehicleTypeId": "Premium", "distance": 31000, "duration": 1800, "pricingType": 0, "typeRate": 0, "pickup": [ 108.172218322754, 16.0609512329102 ], "destination": [ 108.249809265137, 16.0394554138184 ], "packageRateId": "", "services": [] } |
        Then I get return info with passenger info
            | res                                                                                                                                                                                                                                                                                                                                                                                                                                             |
            | {"response":{"basicFare":302,"etaFare":747.2,"currencyISO":"CAD","airportFee":0,"meetDriverFee":0,"rushHourFee":9.99,"techFee":1.5,"bookingFee":0,"tollFee":0,"tax":25.34,"tip":358.37,"minFare":20,"normalFare":true,"route":"","vehicleType":"Premium","min":false,"otherFees":50,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"typeRate":0,"extraDistanceFee":0,"extraDurationFee":0,"taxValue":0,"tipValue":0},"returnCode":200} |


    Scenario: 17. Connect socket & get eta fare
        Given I request connect socket to "https://dispatcher.lab.qup.vn"
        And I want register socket with data
            | platform | phone                                 | fleetId | appType   | verifyCode | ime                                  | appName   | rv       | password |
            | android  | {"number":"909111222","country":"VN"} | tappcar | passenger | 1211       | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | 4.6.2800 |          |
        When I send a request to estimate fare with params based on table below
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                       |
            | { "bookFrom": "TappCar", "city": "550000__Đà Nẵng_Việt Nam", "meetDriver": -1, "bookType": 0, "pickupTime": "Now", "zipCodeTo": "550000", "zipCodeFrom": "550000", "fleetId": "tappcar", "userId": "5c0f6dc79eb4565ec59f9342", "vehicleTypeId": "Premium", "distance": 5542, "duration": 808, "pricingType": 0, "typeRate": 0, "pickup": [ 108.213188,16.068396 ], "destination": [ 108.247299,16.084240 ], "packageRateId": "", "services": [] } |
        Then I get return info with passenger info
            | res                                                                                                                                                                                                                                                                                                                                                                                                                                                |
            | {"response":{"basicFare":84.44,"etaFare":299.03,"currencyISO":"CAD","airportFee":0,"meetDriverFee":0,"rushHourFee":9.99,"techFee":1.5,"bookingFee":0,"tollFee":0,"tax":10.11,"tip":142.99,"minFare":20,"normalFare":true,"route":"","vehicleType":"Premium","min":false,"otherFees":50,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"typeRate":0,"extraDistanceFee":0,"extraDurationFee":0,"taxValue":0,"tipValue":0},"returnCode":200} |


    Scenario: 18. Connect socket & get eta fare (check minimum with vehicle is SUV)
        Given I request connect socket to "https://dispatcher.lab.qup.vn"
        And I want register socket with data
            | platform | phone                                 | fleetId | appType   | verifyCode | ime                                  | appName   | rv       | password |
            | android  | {"number":"909111222","country":"VN"} | tappcar | passenger | 1211       | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | 4.6.2800 |          |
        When I send a request to estimate fare with params based on table below
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                            |
            | { "bookFrom": "TappCar", "city": "550000__Đà Nẵng_Việt Nam", "meetDriver": -1, "bookType": 0, "pickupTime": "Reservation", "zipCodeTo": "550000", "zipCodeFrom": "550000", "fleetId": "tappcar", "userId": "5c0f6dc79eb4565ec59f9342", "vehicleTypeId": "SUV", "distance": 1000, "duration": 300, "pricingType": 0, "typeRate": 0, "pickup": [ 108.172924, 16.061150 ], "destination": [ 108.175781,16.057626 ], "packageRateId": "", "services": [] } |
        Then I get return info with passenger info
            | res                                                                                                                                                                                                                                                                                                                                                                                                                               |
            | {"response":{"basicFare":27.5,"etaFare":207.5,"currencyISO":"CAD","airportFee":0,"meetDriverFee":0,"rushHourFee":0,"techFee":1.5,"bookingFee":0,"tollFee":0,"tax":7,"tip":99,"minFare":100,"normalFare":true,"route":"","vehicleType":"SUV","min":true,"otherFees":50,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"typeRate":0,"extraDistanceFee":0,"extraDurationFee":0,"taxValue":0,"tipValue":0},"returnCode":200} |

    #Pickup location in zone & flat rate
    Scenario: 19. Connect socket & get eta flat rate (Route 1 Fare)
        Given I request connect socket to "https://dispatcher.lab.qup.vn"
        And I want register socket with data
            | platform | phone                                 | fleetId | appType   | verifyCode | ime                                  | appName   | rv       | password |
            | android  | {"number":"909111222","country":"VN"} | tappcar | passenger | 1211       | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | 4.6.2800 |          |
        When I send a request to estimate fare with params based on table below
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                     |
            | { "bookFrom": "TappCar", "city": "550000__Đà Nẵng_Việt Nam", "meetDriver": -1, "bookType": 0, "pickupTime": "Now", "zipCodeTo": "550000", "zipCodeFrom": "550000", "fleetId": "tappcar", "userId": "5c0f6dc79eb4565ec59f9342", "vehicleTypeId": "Premium", "distance": 10000, "duration": 1300, "pricingType": 0, "typeRate": 0, "pickup": [108.219906,16.085142], "destination": [108.263725,16.013376], "packageRateId": "", "services": [] } |
        Then I get return info with passenger info
            | res                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
            | {"response":{"basicFare":19.99,"etaFare":166.26,"currencyISO":"CAD","airportFee":0,"meetDriverFee":0,"rushHourFee":9.99,"techFee":1.5,"bookingFee":0,"tollFee":0,"tax":5.6,"tip":79.18,"minFare":0,"normalFare":false,"route":"3/2 - Hyatt","vehicleType":"Premium","min":false,"otherFees":50,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"typeRate":1,"extraDistanceFee":0,"extraDurationFee":0,"taxValue":0,"tipValue":0},"returnCode":200} |


    Scenario: 20. Connect socket & get eta flat rate (Route 2 Fare)
        Given I request connect socket to "https://dispatcher.lab.qup.vn"
        And I want register socket with data
            | platform | phone                                 | fleetId | appType   | verifyCode | ime                                  | appName   | rv       | password |
            | android  | {"number":"909111222","country":"VN"} | tappcar | passenger | 1211       | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | 4.6.2800 |          |
        When I send a request to estimate fare with params based on table below
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                     |
            | { "bookFrom": "TappCar", "city": "550000__Đà Nẵng_Việt Nam", "meetDriver": -1, "bookType": 0, "pickupTime": "Now", "zipCodeTo": "550000", "zipCodeFrom": "550000", "fleetId": "tappcar", "userId": "5c0f6dc79eb4565ec59f9342", "vehicleTypeId": "Premium", "distance": 10000, "duration": 1300, "pricingType": 0, "typeRate": 0, "pickup": [108.263725,16.013376], "destination": [108.219906,16.085142], "packageRateId": "", "services": [] } |
        Then I get return info with passenger info
            | res                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
            | {"response":{"basicFare":21.99,"etaFare":170.38,"currencyISO":"CAD","airportFee":0,"meetDriverFee":0,"rushHourFee":9.99,"techFee":1.5,"bookingFee":0,"tollFee":0,"tax":5.74,"tip":81.16,"minFare":0,"normalFare":false,"route":"3/2 - Hyatt","vehicleType":"Premium","min":false,"otherFees":50,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"typeRate":1,"extraDistanceFee":0,"extraDurationFee":0,"taxValue":0,"tipValue":0},"returnCode":200} |


    #Pickup location in zone & flat rate (round trip)
    Scenario: 21. Connect socket & get eta flat rate (round trip)
        Given I request connect socket to "https://dispatcher.lab.qup.vn"
        And I want register socket with data
            | platform | phone                                 | fleetId | appType   | verifyCode | ime                                  | appName   | rv       | password |
            | ios      | {"number":"909111222","country":"VN"} | tappcar | passenger | 1211       | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | 4.6.2800 |          |
        When I send a request to estimate fare with params based on table below
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                     |
            | { "bookFrom": "TappCar", "city": "550000__Đà Nẵng_Việt Nam", "meetDriver": -1, "bookType": 4, "pickupTime": "Now", "zipCodeTo": "550000", "zipCodeFrom": "550000", "fleetId": "tappcar", "userId": "5c0f6dc79eb4565ec59f9342", "vehicleTypeId": "Premium", "distance": 10000, "duration": 1300, "pricingType": 0, "typeRate": 0, "pickup": [108.263725,16.013376], "destination": [108.219906,16.085142], "packageRateId": "", "services": [] } |
        Then I get return info with passenger info
            | res                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
            | {"response":{"basicFare":35.55,"etaFare":198.31,"currencyISO":"CAD","airportFee":0,"meetDriverFee":0,"rushHourFee":9.99,"techFee":1.5,"bookingFee":0,"tollFee":0,"tax":6.69,"tip":94.58,"minFare":0,"normalFare":false,"route":"3/2 - Hyatt","vehicleType":"Premium","min":false,"otherFees":50,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"typeRate":3,"extraDistanceFee":0,"extraDurationFee":0,"taxValue":0,"tipValue":0},"returnCode":200} |


    #Pickup location in zone & hourly rate (hourly trip)
    Scenario: 22. Connect socket & get eta Hourly rate (hourly trip)
        Given I request connect socket to "https://dispatcher.lab.qup.vn"
        And I want register socket with data
            | platform | phone                                 | fleetId | appType   | verifyCode | ime                                  | appName   | rv       | password |
            | ios      | {"number":"909111222","country":"VN"} | tappcar | passenger | 1211       | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | 4.6.2800 |          |
        When I send a request to estimate fare with params based on table below
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
            | { "bookFrom": "TappCar", "city": "550000__Đà Nẵng_Việt Nam", "meetDriver": -1, "bookType": 3, "pickupTime": "Now", "zipCodeTo": "550000", "zipCodeFrom": "550000", "fleetId": "tappcar", "userId": "5c0f6dc79eb4565ec59f9342", "vehicleTypeId": "Premium", "distance": 10000, "duration": 1300, "pricingType": 0, "typeRate": 0, "pickup": [108.263725,16.013376], "destination": [108.219906,16.085142], "packageRateId": "58f81478e4b0e611751d03ef", "services": [] } |
        Then I get return info with passenger info
            | res                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
            | {"response":{"basicFare":1780,"etaFare":3812.46,"currencyISO":"CAD","airportFee":0,"meetDriverFee":0,"rushHourFee":19.98,"techFee":1.5,"bookingFee":0,"tollFee":0,"tax":129.5,"tip":1831.48,"minFare":0,"normalFare":false,"route":"","vehicleType":"Premium","min":false,"otherFees":50,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"packages":[{"duration":1,"feesByCurrencies":[{"currencyISO":"CAD","basedFee":100,"extraDuration":80,"extraDistance":8}],"coveredDistance":9999,"extraDistanceFee":0,"name":"Premium: 1 Hour","extraDurationFee":1680,"_id":"58f81478e4b0e611751d03ef","type":"hour","value":3812.46},{"duration":1,"feesByCurrencies":[{"currencyISO":"CAD","basedFee":899,"extraDuration":799,"extraDistance":14.99}],"coveredDistance":500,"extraDistanceFee":0,"name":"Premium: 1 Day","extraDurationFee":799,"_id":"5c0f450aaa612f2599146ed2","type":"day","value":3643.54}],"typeRate":2,"extraDistanceFee":0,"extraDurationFee":1680,"taxValue":0,"tipValue":0},"returnCode":200} |


    Scenario: 23. Connect socket & get eta Hourly rate (hourly trip) & reservation
        Given I request connect socket to "https://dispatcher.lab.qup.vn"
        And I want register socket with data
            | platform | phone                                 | fleetId | appType   | verifyCode | ime                                  | appName   | rv       | password |
            | ios      | {"number":"909111222","country":"VN"} | tappcar | passenger | 1211       | A1E17271-7671-40EB-851B-71D4515652B8 | tappcar_p | 4.6.2800 |          |
        When I send a request to estimate fare with params based on table below
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
            | { "bookFrom": "TappCar", "city": "550000__Đà Nẵng_Việt Nam", "meetDriver": -1, "bookType": 3, "pickupTime": "2018-12-30 15:28", "zipCodeTo": "550000", "zipCodeFrom": "550000", "fleetId": "tappcar", "userId": "5c0f6dc79eb4565ec59f9342", "vehicleTypeId": "Premium", "distance": 10000, "duration": 1300, "pricingType": 0, "typeRate": 0, "pickup": [108.263725,16.013376], "destination": [108.219906,16.085142], "packageRateId": "5c0f450aaa612f2599146ed2", "services": [] } |
        Then I get return info with passenger info
            | res                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
            | {"response":{"basicFare":1698,"etaFare":3643.54,"currencyISO":"CAD","airportFee":0,"meetDriverFee":0,"rushHourFee":19.98,"techFee":1.5,"bookingFee":0,"tollFee":0,"tax":123.76,"tip":1750.3,"minFare":0,"normalFare":false,"route":"","vehicleType":"Premium","min":false,"otherFees":50,"promoAmount":0,"bookingFeeActive":false,"serviceFee":0,"packages":[{"duration":1,"feesByCurrencies":[{"currencyISO":"CAD","basedFee":100,"extraDuration":80,"extraDistance":8}],"coveredDistance":9999,"extraDistanceFee":0,"name":"Premium: 1 Hour","extraDurationFee":1680,"_id":"58f81478e4b0e611751d03ef","type":"hour","value":3812.46},{"duration":1,"feesByCurrencies":[{"currencyISO":"CAD","basedFee":899,"extraDuration":799,"extraDistance":14.99}],"coveredDistance":500,"extraDistanceFee":0,"name":"Premium: 1 Day","extraDurationFee":799,"_id":"5c0f450aaa612f2599146ed2","type":"day","value":3643.54}],"typeRate":2,"extraDistanceFee":0,"extraDurationFee":799,"taxValue":0,"tipValue":0},"returnCode":200} |


