Feature: Request Booking from API
    Everybody wants to know when customer is traveler

    Scenario: 1. Request Booking by API
        Given Get token when login account 3rd
        When I request booking from API
        Then Booking create successful
        And I should have "Booking" document in database with "1" Booking ID

    Scenario: 2. Request Booking by API with Booking Type = 0 & Payment Type = 2
        Given Get token when login Account 3rd from "local"
        When I request booking from API when custom data
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
            | { "psgInfo": { "phone": "+12063336666", "firstName": "Auto Test", "lastName": "Demo 123", "email": "tester.qup@gmail.com", "creditInfo": { "cardNumber": "5555555555554444", "cardHolder": "Auto", "postalCode": "98789", "expiredDate": "12/2022", "cvv": "123" } }, "request": { "pickup": { "address": "Da Nang Software Park, Thạch Thang, Hải Châu, Đà Nẵng", "geo": [108.222198, 16.075792], "timezone": "Asia/Saigon" }, "destination": { "address": "Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng", "geo": [108.266139, 16.007381], "timezone": "Asia/Saigon" }, "pickUpTime": "Now", "vehicleTypeRequest": "Bike", "type": 0, "paymentType": 2, "note": "Auto test api", "promo": "", "rideSharing": false, "tip": 10.99, "packageRateId": "5b3d8590e4b0edd700de78cf" }, "dispatch3rd": false, "corporateInfo": { "division": "test", "managerEmail": "test@gmail.com", "corpId": "123", "managerName": "", "costCentre": "", "department": "", "corporateId": "5b3d86a2e4b0edd700de78d5", "clientCaseMatter": "", "chargeCode": "" } } |
        Then Booking create successful
        And I should have "Booking" document in database with "1" Booking ID


    Scenario: 3. Request Booking by API with Booking Type = 0 & Payment Type = 1 (From Airport)
        Given Get token when login Account 3rd from "local"
        When I request booking from API when custom data
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
            | { "psgInfo": { "phone": "+12063336666", "firstName": "Auto Test", "lastName": "Demo 123", "email": "tester.qup@gmail.com", "creditInfo": { "cardNumber": "5555555555554444", "cardHolder": "Auto", "postalCode": "98789", "expiredDate": "12/2022", "cvv": "123" } }, "request": { "pickup": { "address": "Cảng Hàng Không Quốc Tế Đà Nẵng, Duy Tân, Hải Châu, Đà Nẵng", "geo": [108.201338, 16.055583], "timezone": "Asia/Saigon" }, "destination": { "address": "Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng", "geo": [108.266139, 16.007381], "timezone": "Asia/Saigon" }, "pickUpTime": "Now", "vehicleTypeRequest": "Bike", "type": 0, "paymentType": 1, "note": "Auto test api", "promo": "", "rideSharing": false, "tip": 10.99, "packageRateId": "5b3d8590e4b0edd700de78cf" }, "dispatch3rd": false, "corporateInfo": { "division": "test", "managerEmail": "test@gmail.com", "corpId": "123", "managerName": "", "costCentre": "", "department": "", "corporateId": "5b3d86a2e4b0edd700de78d5", "clientCaseMatter": "", "chargeCode": "" } } |
        Then Booking create successful
        And I should have "Booking" document in database with "1" Booking ID

    Scenario: 4. Request Booking by API with Booking Type = 1 & Payment Type = 2 (From Airport)
        Given Get token when login Account 3rd from "local"
        When I request booking from API when custom data
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
            | { "psgInfo": { "phone": "+12063336666", "firstName": "Auto Test", "lastName": "Demo 123", "email": "tester.qup@gmail.com", "creditInfo": { "cardNumber": "5555555555554444", "cardHolder": "Auto", "postalCode": "98789", "expiredDate": "12/2022", "cvv": "123" } }, "request": { "pickup": { "address": "Cảng Hàng Không Quốc Tế Đà Nẵng, Duy Tân, Hải Châu, Đà Nẵng", "geo": [108.201338, 16.055583], "timezone": "Asia/Saigon" }, "destination": { "address": "Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng", "geo": [108.266139, 16.007381], "timezone": "Asia/Saigon" }, "pickUpTime": "Now", "vehicleTypeRequest": "Bike", "type": 1, "paymentType": 1, "note": "Auto test api", "promo": "", "rideSharing": false, "tip": 10.99, "packageRateId": "5b3d8590e4b0edd700de78cf" }, "dispatch3rd": false, "corporateInfo": { "division": "test", "managerEmail": "test@gmail.com", "corpId": "123", "managerName": "", "costCentre": "", "department": "", "corporateId": "5b3d86a2e4b0edd700de78d5", "clientCaseMatter": "", "chargeCode": "" } } |
        Then I should get an error object in returned data with errorCode "400"
            | res                                                                                                                                                                                                     |
            | {"error":{"code":"ValidationError","details":[{"message":"\"type\" must be one of [0, 3, 4]","path":"request.type","type":"any.allowOnly","context":{"valids":[0,3,4],"key":"type"}}]},"response":null} |

    Scenario: 5. Request Booking by API with Booking Type = 0 & Payment Type = 1 (To Airport)
        Given Get token when login Account 3rd from "local"
        When I request booking from API when custom data
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
            | { "psgInfo": { "phone": "+12063336666", "firstName": "Auto Test", "lastName": "Demo 123", "email": "tester.qup@gmail.com", "creditInfo": { "cardNumber": "5555555555554444", "cardHolder": "Auto", "postalCode": "98789", "expiredDate": "12/2022", "cvv": "123" } }, "request": { "pickup": { "address": "Cocobay Da Nang, Vietnam, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng", "geo": [108.284512, 15.966895], "timezone": "Asia/Saigon" }, "destination": { "address": "Da Nang International Airport, Duy Tân, Hải Châu, Đà Nẵng", "geo": [108.201381, 16.055624], "timezone": "Asia/Saigon" }, "pickUpTime": "2018-07-15 12:12", "vehicleTypeRequest": "Bike", "type": 0, "paymentType": 1, "note": "Auto test api", "promo": "", "rideSharing": false, "tip": 10.99, "packageRateId": "5b3d8590e4b0edd700de78cf" }, "dispatch3rd": false, "corporateInfo": { "division": "test", "managerEmail": "test@gmail.com", "corpId": "123", "managerName": "", "costCentre": "", "department": "", "corporateId": "5b3d86a2e4b0edd700de78d5", "clientCaseMatter": "", "chargeCode": "" } } |
        Then Booking create successful
        And I should have "Booking" document in database with "1" Booking ID


