Feature: Request Booking from API when customer request booking is hourly
    Everybody wants to know when customer request booking is hourly

    Scenario: 1. Request Booking by API with Booking "type":3 & "paymentType":2 & Corporate don't have Hourly Rate is "packageRateId": "999999999999999999999999"
        Given Get token when login Account 3rd from "local"
        When I request booking from API when custom data
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
            | { "psgInfo": { "phone": "+12063337778", "firstName": "Auto Test", "lastName": "Demo 123", "email": "tester.qup@gmail.com", "creditInfo": { "cardNumber": "5555555555554444", "cardHolder": "Auto", "postalCode": "98789", "expiredDate": "12/2022", "cvv": "123" } }, "request": { "pickup": { "address": "Da Nang Software Park, Thạch Thang, Hải Châu, Đà Nẵng", "geo": [108.222198, 16.075792], "timezone": "Asia/Saigon" }, "destination": { "address": "Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng", "geo": [108.266139, 16.007381], "timezone": "Asia/Saigon" }, "pickUpTime": "Now", "vehicleTypeRequest": "Bike", "type": 3, "paymentType": 2, "note": "Auto test api", "promo": "", "rideSharing": false, "tip": 13, "packageRateId": "999999999999999999999999" }, "dispatch3rd": false, "corporateInfo": { "division": "test", "managerEmail": "test@gmail.com", "corpId": "123", "managerName": "", "costCentre": "", "department": "", "corporateId": "5b3d86a2e4b0edd700de78d5", "clientCaseMatter": "", "chargeCode": "" } } |
        Then I should get an error object in returned data with errorCode "400"
            | res                                                                                                                                      |
            | {"response":null,"error":{"code":false,"info":{"packagesRate":false,"error_description":["Packages Rates not found"],"error_code":310}}} |

    Scenario: 2. Request Booking by API with Booking "type":3 & "paymentType":2 & Fleet don't have Hourly Rate is "packageRateId": "999999999999999999999999"
        Given Get token when login Account 3rd from "local"
        When I request booking from API when custom data
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
            | { "psgInfo": { "phone": "+12058889999", "firstName": "Auto Test", "lastName": "Demo 123", "email": "tester.qup@gmail.com", "creditInfo": { "cardNumber": "5555555555554444", "cardHolder": "Auto", "postalCode": "98789", "expiredDate": "12/2022", "cvv": "123" } }, "request": { "pickup": { "address": "Da Nang Software Park, Thạch Thang, Hải Châu, Đà Nẵng", "geo": [108.222198, 16.075792], "timezone": "Asia/Saigon" }, "destination": { "address": "Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng", "geo": [108.266139, 16.007381], "timezone": "Asia/Saigon" }, "pickUpTime": "Now", "vehicleTypeRequest": "Bike", "type": 3, "paymentType": 2, "note": "Auto test api", "promo": "", "rideSharing": false, "tip": 13, "packageRateId": "999999999999999999999999" }, "dispatch3rd": false, "corporateInfo": { "division": "", "managerEmail": "", "corpId": "", "managerName": "", "costCentre": "", "department": "", "corporateId": "", "clientCaseMatter": "", "chargeCode": "" } } |
        Then I should get an error object in returned data with errorCode "400"
            | res                                                                                                                                      |
            | {"response":null,"error":{"code":false,"info":{"packagesRate":false,"error_description":["Packages Rates not found"],"error_code":310}}} |


    Scenario: 3. Request Booking by API with Booking "type":3 & "paymentType":2 & Corporate don't setup "Add different rates" & Fleet have Hourly Rate "packageRateId":"5b3d8590e4b0edd700de78cf"
        Given Get token when login Account 3rd from "local"
        When I request booking from API when custom data
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
            | { "psgInfo": { "phone": "+12063337778", "firstName": "Auto Test", "lastName": "Demo 123", "email": "tester.qup@gmail.com", "creditInfo": { "cardNumber": "5555555555554444", "cardHolder": "Auto", "postalCode": "98789", "expiredDate": "12/2022", "cvv": "123" } }, "request": { "pickup": { "address": "Da Nang Software Park, Thạch Thang, Hải Châu, Đà Nẵng", "geo": [108.222198, 16.075792], "timezone": "Asia/Saigon" }, "destination": { "address": "Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng", "geo": [108.266139, 16.007381], "timezone": "Asia/Saigon" }, "pickUpTime": "Now", "vehicleTypeRequest": "Bike", "type": 3, "paymentType": 2, "note": "Auto test api", "promo": "", "rideSharing": false, "tip": 13, "packageRateId": "5b3d8590e4b0edd700de78cf" }, "dispatch3rd": false, "corporateInfo": { "division": "test", "managerEmail": "test@gmail.com", "corpId": "123", "managerName": "", "costCentre": "", "department": "", "corporateId": "5b3d86a2e4b0edd700de78d5", "clientCaseMatter": "", "chargeCode": "" } } |
        Then I should get an error object in returned data with errorCode "400"
            | res                                                                                                                                      |
            | {"response":null,"error":{"code":false,"info":{"packagesRate":false,"error_description":["Packages Rates not found"],"error_code":310}}} |


    Scenario: 4. Request Booking by API with Booking "type":3 & "paymentType":2 & Corporate have Hourly Rate "packageRateId":"5b456341e4b02d2554662d8a"
        Given Get token when login Account 3rd from "local"
        When I request booking from API when custom data
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
            | { "psgInfo": { "phone": "+12063335555", "firstName": "Auto Test", "lastName": "Demo 123", "email": "tester.qup@gmail.com", "creditInfo": { "cardNumber": "5555555555554444", "cardHolder": "Auto", "postalCode": "98789", "expiredDate": "12/2022", "cvv": "123" } }, "request": { "pickup": { "address": "Da Nang Software Park, Thạch Thang, Hải Châu, Đà Nẵng", "geo": [108.222198, 16.075792], "timezone": "Asia/Saigon" }, "destination": { "address": "Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng", "geo": [108.266139, 16.007381], "timezone": "Asia/Saigon" }, "pickUpTime": "Now", "vehicleTypeRequest": "Bike", "type": 3, "paymentType": 2, "note": "Auto test api", "promo": "", "rideSharing": false, "tip": 13, "packageRateId": "5b456341e4b02d2554662d8a" }, "dispatch3rd": false, "corporateInfo": { "division": "Auto for Division", "managerEmail": "manageremail.qup@gmail.com", "corpId": "9999-000999", "managerName": "Auto Bot Name", "costCentre": "Auto Bot Cost", "department": "Auto Bot Deparment", "corporateId": "5b456208e4b02d2554662d82", "clientCaseMatter": "VN83883", "chargeCode": "9902929" } } |
        Then I should have "Booking" document in database with "1" Booking ID
        And I should have "Booking" document in database with below expected data
            | specifiedInfo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
            | [{"platform":"API","bookFrom":"API","travelerType":1,"fleetId":"hoanglocal","fleetName":"Hoang Fleet","reservation":false,"pricingType":0,"currencyISO":"VND","currencySymbol":"đ","dispatch3rd":false,"request":{ "pickUpTime":"Now","vehicleTypeRequest":"Bike","promo":"","rideSharing":false,"tip":0,"packageRateId":"5b456341e4b02d2554662d8a","psgFleetId":"hoanglocal","packageRateName":"Auto Test Hourly 2h","duration":2,"serviceActive":false,"paymentType":2,"type":3,"hourly":0,"moreInfo":{"flightInfo":{"type":-1,"flightNumber":"","airline":""}},"operatorNote":"","note":"Auto test api","vehicleType":["Bike"],"destination":{"businessName":"","zipCode":"","geo":[108.266139,16.007381],"offset":"+07:00","timezone":"Asia/Saigon","address":"Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng"},"pickup":{"address":"Da Nang Software Park, Thạch Thang, Hải Châu, Đà Nẵng","businessName":"","offset":"+07:00","timezone":"Asia/Saigon","zipCode":"","geo":[108.222198,16.075792]},"services":[],"typeRate":0},"bookingRideSharing":[],"dispatchRideSharing":false,"corporateInfo":{"division":"Auto for Division","managerEmail":"manageremail.qup@gmail.com","corpId":"9999-000999","managerName":"Auto Bot Name","costCentre":"Auto Bot Cost","department":"Auto Bot Deparment","corporateId":"5b456208e4b02d2554662d82","clientCaseMatter":"VN83883","chargeCode":"9902929","name":"QUp Auto Test"},"psgInfo":{"firstName":"Auto Test","lastName":"Demo 123","email":"tester.qup@gmail.com","phone":"+12063335555","fullName":"Auto Test Demo 123","creditInfo":{"cardMask":"XXXXXXXXXXXX4444","gateway":"Stripe"},"rank":0},"dispatchType":0}] |
        And Booking create successful


    Scenario: 5. Request Booking by API with Booking "type":3 & "paymentType":2 & Fleet have Hourly Rate "packageRateId":"5b3d8590e4b0edd700de78cf"
        Given Get token when login Account 3rd from "local"
        When I request booking from API when custom data
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
            | { "psgInfo": { "phone": "+12058889999", "firstName": "Auto Test", "lastName": "Demo 123", "email": "tester.qup@gmail.com", "creditInfo": { "cardNumber": "5555555555554444", "cardHolder": "Auto", "postalCode": "98789", "expiredDate": "12/2022", "cvv": "123" } }, "request": { "pickup": { "address": "Da Nang Software Park, Thạch Thang, Hải Châu, Đà Nẵng", "geo": [108.222198, 16.075792], "timezone": "Asia/Saigon" }, "destination": { "address": "Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng", "geo": [108.266139, 16.007381], "timezone": "Asia/Saigon" }, "pickUpTime": "Now", "vehicleTypeRequest": "Bike", "type": 3, "paymentType": 2, "note": "Auto test api", "promo": "", "rideSharing": false, "tip": 13, "packageRateId": "5b3d8590e4b0edd700de78cf" }, "dispatch3rd": false, "corporateInfo": { "division": "", "managerEmail": "", "corpId": "", "managerName": "", "costCentre": "", "department": "", "corporateId": "", "clientCaseMatter": "", "chargeCode": "" } } |
        Then I should have "Booking" document in database with "1" Booking ID
        And I should have "Booking" document in database with below expected data
            | specifiedInfo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
            | [{"platform":"API","bookFrom":"API","travelerType":0,"fleetId":"hoanglocal","fleetName":"Hoang Fleet","reservation":false,"pricingType":0,"currencyISO":"VND","currencySymbol":"đ","dispatch3rd":false,"request":{ "pickUpTime":"Now","vehicleTypeRequest":"Bike","promo":"","rideSharing":false,"tip":0,"packageRateId":"5b3d8590e4b0edd700de78cf","psgFleetId":"hoanglocal","packageRateName":"1 Hour","duration":1,"serviceActive":false,"paymentType":2,"type":3,"hourly":0,"moreInfo":{"flightInfo":{"type":-1,"flightNumber":"","airline":""}},"operatorNote":"","note":"Auto test api","vehicleType":["Bike"],"destination":{"businessName":"","zipCode":"","geo":[108.266139,16.007381],"offset":"+07:00","timezone":"Asia/Saigon","address":"Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng"},"pickup":{"address":"Da Nang Software Park, Thạch Thang, Hải Châu, Đà Nẵng","businessName":"","offset":"+07:00","timezone":"Asia/Saigon","zipCode":"","geo":[108.222198,16.075792]},"services":[],"typeRate":0},"bookingRideSharing":[],"dispatchRideSharing":false,"corporateInfo":{"division":"","managerEmail":"","corpId":"","managerName":"","costCentre":"","department":"","corporateId":"","clientCaseMatter":"","chargeCode":""},"psgInfo":{"firstName":"Auto Test","lastName":"Demo 123","email":"tester.qup@gmail.com","phone":"+12058889999","fullName":"Auto Test Demo 123","creditInfo":{"cardMask":"XXXXXXXXXXXX4444","gateway":"Stripe"},"rank":0},"dispatchType":0}] |
        And Booking create successful

