Feature: Request Booking from API when customer request booking is Flat Rate
    Everybody wants to know when customer request booking is Flat Rate


    Scenario: 1. Request Booking by API with Booking "type":0 & "paymentType":2 & Route 1 (First location -> Second location)
        Given Get token when login Account 3rd from "local"
        When I request booking from API when custom data
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
            | { "psgInfo": { "phone": "+12058889999", "firstName": "Auto Test", "lastName": "Demo 123", "email": "tester.qup@gmail.com", "creditInfo": { "cardNumber": "5555555555554444", "cardHolder": "Auto", "postalCode": "98789", "expiredDate": "12/2022", "cvv": "123" } }, "request": { "pickup": { "address": "3 Tháng 2, Hải Châu, Đà Nẵng", "geo": [108.2189982, 16.0856233], "timezone": "Asia/Saigon" }, "destination": { "address": "Hyatt Regency Danang Resort and Spa, Hòa Hải, Danang, Đà Nẵng", "geo": [108.2637083, 16.0131183], "timezone": "Asia/Saigon" }, "pickUpTime": "Now", "vehicleTypeRequest": "Bike", "type": 0, "paymentType": 2, "note": "Auto test api", "promo": "", "rideSharing": false, "tip": 13, "packageRateId": "" }, "dispatch3rd": false, "corporateInfo": { "division": "", "managerEmail": "", "corpId": "", "managerName": "", "costCentre": "", "department": "", "corporateId": "", "clientCaseMatter": "", "chargeCode": "" } } |

        Then I should have "Booking" document in database with "1" Booking ID
        And I should have "Booking" document in database with below expected data
            | specifiedInfo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
            | [{"platform":"API","bookFrom":"API","travelerType":0,"fleetId":"hoanglocal","fleetName":"Hoang Fleet","reservation":false,"pricingType":0,"currencyISO":"VND","currencySymbol":"đ","dispatch3rd":false,"request":{ "pickUpTime":"Now","vehicleTypeRequest":"Bike","promo":"","rideSharing":false,"tip":0,"packageRateId":"","psgFleetId":"hoanglocal","serviceActive":false,"paymentType":2,"type":0,"hourly":0,"moreInfo":{"flightInfo":{"type":-1,"flightNumber":"","airline":""}},"operatorNote":"","note":"Auto test api","vehicleType":["Bike"],"destination":{"businessName":"","zipCode":"","geo":[108.2637083,16.0131183],"offset":"+07:00","timezone":"Asia/Saigon","address":"Hyatt Regency Danang Resort and Spa, Hòa Hải, Danang, Đà Nẵng"},"pickup":{"address":"3 Tháng 2, Hải Châu, Đà Nẵng","businessName":"","offset":"+07:00","timezone":"Asia/Saigon","zipCode":"","geo":[108.2189982,16.0856233]},"typeRate":0},"bookingRideSharing":[],"dispatchRideSharing":false,"corporateInfo":{"division":"","managerEmail":"","corpId":"","managerName":"","costCentre":"","department":"","corporateId":"","clientCaseMatter":"","chargeCode":""},"psgInfo":{"firstName":"Auto Test","lastName":"Demo 123","email":"tester.qup@gmail.com","phone":"+12058889999","fullName":"Auto Test Demo 123","creditInfo":{"cardMask":"XXXXXXXXXXXX4444","gateway":"Stripe"},"rank":0},"dispatchType":0}] |
        And Booking create successful

    Scenario: 2. Request Booking by API with Booking "type":0 & "paymentType":2 & Route 2 (Second location -> First location)
        Given Get token when login Account 3rd from "local"
        When I request booking from API when custom data
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
            | { "psgInfo": { "phone": "+12058889999", "firstName": "Auto Test", "lastName": "Demo 123", "email": "tester.qup@gmail.com", "creditInfo": { "cardNumber": "5555555555554444", "cardHolder": "Auto", "postalCode": "98789", "expiredDate": "12/2022", "cvv": "123" } }, "request": { "pickup": { "address": "Hyatt Regency Danang Resort and Spa, Hòa Hải, Danang, Đà Nẵng", "geo": [108.2637083, 16.0131183], "timezone": "Asia/Saigon" }, "destination": { "address": "3 Tháng 2, Hải Châu, Đà Nẵng", "geo": [108.2189982, 16.0856233], "timezone": "Asia/Saigon" }, "pickUpTime": "Now", "vehicleTypeRequest": "Bike", "type": 0, "paymentType": 2, "note": "Auto test api", "promo": "", "rideSharing": false, "tip": 13, "packageRateId": "" }, "dispatch3rd": false, "corporateInfo": { "division": "", "managerEmail": "", "corpId": "", "managerName": "", "costCentre": "", "department": "", "corporateId": "", "clientCaseMatter": "", "chargeCode": "" } } |

        Then I should have "Booking" document in database with "1" Booking ID
        And I should have "Booking" document in database with below expected data
            | specifiedInfo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
            | [{"platform":"API","bookFrom":"API","travelerType":0,"fleetId":"hoanglocal","fleetName":"Hoang Fleet","reservation":false,"pricingType":0,"currencyISO":"VND","currencySymbol":"đ","dispatch3rd":false,"request":{ "pickUpTime":"Now","vehicleTypeRequest":"Bike","promo":"","rideSharing":false,"tip":0,"packageRateId":"","psgFleetId":"hoanglocal","serviceActive":false,"paymentType":2,"type":0,"hourly":0,"moreInfo":{"flightInfo":{"type":-1,"flightNumber":"","airline":""}},"operatorNote":"","note":"Auto test api","vehicleType":["Bike"],"destination":{"businessName":"","zipCode":"","geo":[108.2189982,16.0856233],"offset":"+07:00","timezone":"Asia/Saigon","address":"3 Tháng 2, Hải Châu, Đà Nẵng"},"pickup":{"address":"Hyatt Regency Danang Resort and Spa, Hòa Hải, Danang, Đà Nẵng","businessName":"","offset":"+07:00","timezone":"Asia/Saigon","zipCode":"","geo":[108.2637083,16.0131183]},"typeRate":0},"bookingRideSharing":[],"dispatchRideSharing":false,"corporateInfo":{"division":"","managerEmail":"","corpId":"","managerName":"","costCentre":"","department":"","corporateId":"","clientCaseMatter":"","chargeCode":""},"psgInfo":{"firstName":"Auto Test","lastName":"Demo 123","email":"tester.qup@gmail.com","phone":"+12058889999","fullName":"Auto Test Demo 123","creditInfo":{"cardMask":"XXXXXXXXXXXX4444","gateway":"Stripe"},"rank":0},"dispatchType":0}] |
        And Booking create successful
