Feature: Request Booking from API
Everybody wants to know when customer is traveler

# Note

    #Muốn setup request create booking với "paymentType":1,5,6 thì không add "creditInfo" vào "requestBody". Nếu có request "creditInfo" vào "requestBody" thì "paymentType" tự động chuyển về "2"

    Scenario: 1. Request Booking by API with Booking Type = 0 & "paymentType" = 1
        Given Get token when login Account 3rd from "local"
        When I request booking from API when custom data
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
            | { "psgInfo": { "phone": "+12063336666", "firstName": "Auto Test", "lastName": "Demo 123", "email": "tester.qup@gmail.com" }, "request": { "pickup": { "address": "Da Nang Software Park, Thạch Thang, Hải Châu, Đà Nẵng", "geo": [108.222198, 16.075792], "timezone": "Asia/Saigon" }, "destination": { "address": "Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng", "geo": [108.266139, 16.007381], "timezone": "Asia/Saigon" }, "pickUpTime": "Now", "vehicleTypeRequest": "Bike", "type": 0, "paymentType": 1, "note": "Auto test api", "promo": "", "rideSharing": false, "tip": 13, "packageRateId": "5b3d8590e4b0edd700de78cf" }, "dispatch3rd": false, "corporateInfo": { "division": "test", "managerEmail": "test@gmail.com", "corpId": "123", "managerName": "", "costCentre": "", "department": "", "corporateId": "5b3d86a2e4b0edd700de78d5", "clientCaseMatter": "", "chargeCode": "" } } |
        Then Booking create successful
        And I should have "Booking" document in database with "1" Booking ID
        And I should have "Booking" document in database with below expected data
            | specifiedInfo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
            | [{"platform":"API","bookFrom":"API","travelerType":1,"fleetId":"hoanglocal","fleetName":"Hoang Fleet","reservation":false,"pricingType":0,"currencyISO":"VND","currencySymbol":"đ","dispatch3rd":false,"request":{ "pickUpTime":"Now","vehicleTypeRequest":"Bike","promo":"","rideSharing":false,"tip":0,"psgFleetId":"hoanglocal","serviceActive":false,"paymentType":1,"type":0,"hourly":0,"moreInfo":{"flightInfo":{"type":-1,"flightNumber":"","airline":""}},"operatorNote":"","note":"Auto test api","vehicleType":["Bike"],"destination":{"businessName":"","zipCode":"","geo":[108.266139,16.007381],"offset":"+07:00","timezone":"Asia/Saigon","address":"Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng"},"pickup":{"address":"Da Nang Software Park, Thạch Thang, Hải Châu, Đà Nẵng","businessName":"","offset":"+07:00","timezone":"Asia/Saigon","zipCode":"","geo":[108.222198,16.075792]},"services":[],"typeRate":0},"bookingRideSharing":[],"dispatchRideSharing":false,"corporateInfo":{"division":"test","managerEmail":"test@gmail.com","corpId":"123","managerName":"","costCentre":"","department":"","corporateId":"5b3d86a2e4b0edd700de78d5","clientCaseMatter":"","chargeCode":""},"psgInfo":{"firstName":"Auto Test","lastName":"Demo 123","email":"tester.qup@gmail.com","phone":"+12063336666","fullName":"Auto Test Demo 123","rank":0},"dispatchType":0}] |

    Scenario: 2. Request Booking by API with Booking Type = 0 & "paymentType" = 2
        Given Get token when login Account 3rd from "local"
        When I request booking from API when custom data
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
            | { "psgInfo": { "phone": "+12063336666", "firstName": "Auto Test", "lastName": "Demo 123", "email": "tester.qup@gmail.com", "creditInfo": { "cardNumber": "5555555555554444", "cardHolder": "Auto", "postalCode": "98789", "expiredDate": "12/2022", "cvv": "123" } }, "request": { "pickup": { "address": "Da Nang Software Park, Thạch Thang, Hải Châu, Đà Nẵng", "geo": [108.222198, 16.075792], "timezone": "Asia/Saigon" }, "destination": { "address": "Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng", "geo": [108.266139, 16.007381], "timezone": "Asia/Saigon" }, "pickUpTime": "Now", "vehicleTypeRequest": "Bike", "type": 0, "paymentType": 2, "note": "Auto test api", "promo": "", "rideSharing": false, "tip": 13, "packageRateId": "5b3d8590e4b0edd700de78cf" }, "dispatch3rd": false, "corporateInfo": { "division": "test", "managerEmail": "test@gmail.com", "corpId": "123", "managerName": "", "costCentre": "", "department": "", "corporateId": "5b3d86a2e4b0edd700de78d5", "clientCaseMatter": "", "chargeCode": "" } } |
        Then Booking create successful
        And I should have "Booking" document in database with "1" Booking ID
        And I should have "Booking" document in database with below expected data
            | specifiedInfo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
            | [{"platform":"API","bookFrom":"API","travelerType":1,"fleetId":"hoanglocal","fleetName":"Hoang Fleet","reservation":false,"pricingType":0,"currencyISO":"VND","currencySymbol":"đ","dispatch3rd":false,"request":{ "pickUpTime":"Now","vehicleTypeRequest":"Bike","promo":"","rideSharing":false,"tip":0,"psgFleetId":"hoanglocal","serviceActive":false,"paymentType":2,"type":0,"hourly":0,"moreInfo":{"flightInfo":{"type":-1,"flightNumber":"","airline":""}},"operatorNote":"","note":"Auto test api","vehicleType":["Bike"],"destination":{"businessName":"","zipCode":"","geo":[108.266139,16.007381],"offset":"+07:00","timezone":"Asia/Saigon","address":"Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng"},"pickup":{"address":"Da Nang Software Park, Thạch Thang, Hải Châu, Đà Nẵng","businessName":"","offset":"+07:00","timezone":"Asia/Saigon","zipCode":"","geo":[108.222198,16.075792]},"services":[],"typeRate":0},"bookingRideSharing":[],"dispatchRideSharing":false,"corporateInfo":{"division":"test","managerEmail":"test@gmail.com","corpId":"123","managerName":"","costCentre":"","department":"","corporateId":"5b3d86a2e4b0edd700de78d5","clientCaseMatter":"","chargeCode":""},"psgInfo":{"firstName":"Auto Test","lastName":"Demo 123","email":"tester.qup@gmail.com","phone":"+12063336666","fullName":"Auto Test Demo 123","creditInfo":{"cardMask":"XXXXXXXXXXXX4444","gateway":"Stripe"},"rank":0},"dispatchType":0}] |


    Scenario: 3. Request Booking by API with Booking Type = 0 & "paymentType" = 2 (From Airport)
        Given Get token when login Account 3rd from "local"
        When I request booking from API when custom data
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
            | { "psgInfo": { "phone": "+12063336666", "firstName": "Auto Test", "lastName": "Demo 123", "email": "tester.qup@gmail.com", "creditInfo": { "cardNumber": "5555555555554444", "cardHolder": "Auto", "postalCode": "98789", "expiredDate": "12/2022", "cvv": "123" } }, "request": { "pickup": { "address": "Cảng Hàng Không Quốc Tế Đà Nẵng, Duy Tân, Hải Châu, Đà Nẵng", "geo": [108.201338, 16.055583], "timezone": "Asia/Saigon" }, "destination": { "address": "Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng", "geo": [108.266139, 16.007381], "timezone": "Asia/Saigon" }, "pickUpTime": "Now", "vehicleTypeRequest": "Bike", "type": 0, "paymentType": 2, "note": "Auto test api", "promo": "", "rideSharing": false, "tip": 13, "packageRateId": "5b3d8590e4b0edd700de78cf" }, "dispatch3rd": false, "corporateInfo": { "division": "test", "managerEmail": "test@gmail.com", "corpId": "123", "managerName": "", "costCentre": "", "department": "", "corporateId": "5b3d86a2e4b0edd700de78d5", "clientCaseMatter": "", "chargeCode": "" } } |
        Then Booking create successful
        And I should have "Booking" document in database with "1" Booking ID

    Scenario: 4. Request Booking by API with Booking Type = 0 & "paymentType" = 2 (To Airport)
        Given Get token when login Account 3rd from "local"
        When I request booking from API when custom data
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
            | { "psgInfo": { "phone": "+12063336666", "firstName": "Auto Test", "lastName": "Demo 123", "email": "tester.qup@gmail.com", "creditInfo": { "cardNumber": "5555555555554444", "cardHolder": "Auto", "postalCode": "98789", "expiredDate": "12/2022", "cvv": "123" } }, "request": { "pickup": { "address": "Cocobay Da Nang, Vietnam, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng", "geo": [108.284512, 15.966895], "timezone": "Asia/Saigon" }, "destination": { "address": "Da Nang International Airport, Duy Tân, Hải Châu, Đà Nẵng", "geo": [108.201381, 16.055624], "timezone": "Asia/Saigon" }, "pickUpTime": "2018-07-15 12:12", "vehicleTypeRequest": "Bike", "type": 0, "paymentType": 2, "note": "Auto test api", "promo": "", "rideSharing": false, "tip": 13, "packageRateId": "5b3d8590e4b0edd700de78cf" }, "dispatch3rd": false, "corporateInfo": { "division": "test", "managerEmail": "test@gmail.com", "corpId": "123", "managerName": "", "costCentre": "", "department": "", "corporateId": "5b3d86a2e4b0edd700de78d5", "clientCaseMatter": "", "chargeCode": "" } } |
        Then Booking create successful
        And I should have "Booking" document in database with "1" Booking ID

    Scenario: 5. Request Booking by API with Booking Type = 0 & "paymentType" = 5
        Given Get token when login Account 3rd from "local"
        When I request booking from API when custom data
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
            | { "psgInfo": { "phone": "+12063336666", "firstName": "Auto Test", "lastName": "Demo 123", "email": "tester.qup@gmail.com"}, "request": { "pickup": { "address": "Da Nang Software Park, Thạch Thang, Hải Châu, Đà Nẵng", "geo": [108.222198, 16.075792], "timezone": "Asia/Saigon" }, "destination": { "address": "Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng", "geo": [108.266139, 16.007381], "timezone": "Asia/Saigon" }, "pickUpTime": "Now", "vehicleTypeRequest": "Bike", "type": 0, "paymentType": 5, "note": "Auto test api", "promo": "", "rideSharing": false, "tip": 13, "packageRateId": "5b3d8590e4b0edd700de78cf" }, "dispatch3rd": false, "corporateInfo": { "division": "test", "managerEmail": "test@gmail.com", "corpId": "123", "managerName": "", "costCentre": "", "department": "", "corporateId": "5b3d86a2e4b0edd700de78d5", "clientCaseMatter": "", "chargeCode": "" } } |
        Then Booking create successful
        And I should have "Booking" document in database with "1" Booking ID
        And I should have "Booking" document in database with below expected data
            | specifiedInfo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
            | [{"platform":"API","bookFrom":"API","travelerType":1,"fleetId":"hoanglocal","fleetName":"Hoang Fleet","reservation":false,"pricingType":0,"currencyISO":"VND","currencySymbol":"đ","dispatch3rd":false,"request":{ "pickUpTime":"Now","vehicleTypeRequest":"Bike","promo":"","rideSharing":false,"tip":0,"psgFleetId":"hoanglocal","serviceActive":false,"paymentType":5,"type":0,"hourly":0,"moreInfo":{"flightInfo":{"type":-1,"flightNumber":"","airline":""}},"operatorNote":"","note":"Auto test api","vehicleType":["Bike"],"destination":{"businessName":"","zipCode":"","geo":[108.266139,16.007381],"offset":"+07:00","timezone":"Asia/Saigon","address":"Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng"},"pickup":{"address":"Da Nang Software Park, Thạch Thang, Hải Châu, Đà Nẵng","businessName":"","offset":"+07:00","timezone":"Asia/Saigon","zipCode":"","geo":[108.222198,16.075792]},"services":[],"typeRate":0},"bookingRideSharing":[],"dispatchRideSharing":false,"corporateInfo":{"division":"test","managerEmail":"test@gmail.com","corpId":"123","managerName":"","costCentre":"","department":"","corporateId":"5b3d86a2e4b0edd700de78d5","clientCaseMatter":"","chargeCode":""},"psgInfo":{"firstName":"Auto Test","lastName":"Demo 123","email":"tester.qup@gmail.com","phone":"+12063336666","fullName":"Auto Test Demo 123","rank":0},"dispatchType":0}] |


    Scenario: 6. Request Booking by API with Booking Type = 0 & "paymentType" = 6
        Given Get token when login Account 3rd from "local"
        When I request booking from API when custom data
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
            | { "psgInfo": { "phone": "+12063336666", "firstName": "Auto Test", "lastName": "Demo 123", "email": "tester.qup@gmail.com"}, "request": { "pickup": { "address": "Da Nang Software Park, Thạch Thang, Hải Châu, Đà Nẵng", "geo": [108.222198, 16.075792], "timezone": "Asia/Saigon" }, "destination": { "address": "Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng", "geo": [108.266139, 16.007381], "timezone": "Asia/Saigon" }, "pickUpTime": "Now", "vehicleTypeRequest": "Bike", "type": 0, "paymentType": 6, "note": "Auto test api", "promo": "", "rideSharing": false, "tip": 13, "packageRateId": "5b3d8590e4b0edd700de78cf" }, "dispatch3rd": false, "corporateInfo": { "division": "test", "managerEmail": "test@gmail.com", "corpId": "123", "managerName": "", "costCentre": "", "department": "", "corporateId": "5b3d86a2e4b0edd700de78d5", "clientCaseMatter": "", "chargeCode": "" } } |
        Then Booking create successful
        And I should have "Booking" document in database with "1" Booking ID
        And I should have "Booking" document in database with below expected data
            | specifiedInfo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
            | [{"platform":"API","bookFrom":"API","travelerType":1,"fleetId":"hoanglocal","fleetName":"Hoang Fleet","reservation":false,"pricingType":0,"currencyISO":"VND","currencySymbol":"đ","dispatch3rd":false,"request":{ "pickUpTime":"Now","vehicleTypeRequest":"Bike","promo":"","rideSharing":false,"tip":0,"psgFleetId":"hoanglocal","serviceActive":false,"paymentType":6,"type":0,"hourly":0,"moreInfo":{"flightInfo":{"type":-1,"flightNumber":"","airline":""}},"operatorNote":"","note":"Auto test api","vehicleType":["Bike"],"destination":{"businessName":"","zipCode":"","geo":[108.266139,16.007381],"offset":"+07:00","timezone":"Asia/Saigon","address":"Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng"},"pickup":{"address":"Da Nang Software Park, Thạch Thang, Hải Châu, Đà Nẵng","businessName":"","offset":"+07:00","timezone":"Asia/Saigon","zipCode":"","geo":[108.222198,16.075792]},"services":[],"typeRate":0},"bookingRideSharing":[],"dispatchRideSharing":false,"corporateInfo":{"division":"test","managerEmail":"test@gmail.com","corpId":"123","managerName":"","costCentre":"","department":"","corporateId":"5b3d86a2e4b0edd700de78d5","clientCaseMatter":"","chargeCode":""},"psgInfo":{"firstName":"Auto Test","lastName":"Demo 123","email":"tester.qup@gmail.com","phone":"+12063336666","fullName":"Auto Test Demo 123","rank":0},"dispatchType":0}] |

