Feature: Request Booking from API when customer is New traveler
    Everybody wants to know when customer is New traveler

    Scenario: 1. Request Booking by API with Booking Type = 0 & "paymentType" = 2 & New Traveler
        Given Get token when login Account 3rd from "local"
        When I request booking from API when custom data
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
            | { "psgInfo": { "phone": "+12063337779", "firstName": "Auto Test", "lastName": "Demo 123", "email": "tester.qup@gmail.com", "creditInfo": { "cardNumber": "5555555555554444", "cardHolder": "Auto", "postalCode": "98789", "expiredDate": "12/2022", "cvv": "123" } }, "request": { "pickup": { "address": "Da Nang Software Park, Thạch Thang, Hải Châu, Đà Nẵng", "geo": [108.222198, 16.075792], "timezone": "Asia/Saigon" }, "destination": { "address": "Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng", "geo": [108.266139, 16.007381], "timezone": "Asia/Saigon" }, "pickUpTime": "Now", "vehicleTypeRequest": "Bike", "type": 0, "paymentType": 2, "note": "Auto test api", "promo": "", "rideSharing": false, "tip": 10.99, "packageRateId": "5b3d8590e4b0edd700de78cf" }, "dispatch3rd": false, "corporateInfo": { "division": "test", "managerEmail": "test@gmail.com", "corpId": "123", "managerName": "", "costCentre": "", "department": "", "corporateId": "5b3d86a2e4b0edd700de78d5", "clientCaseMatter": "", "chargeCode": "" } } |
        Then Booking create successful
        And I should have "Booking" document in database with "1" Booking ID
        And I should have "Booking" document in database with below expected data
            | specifiedInfo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
            | [{"platform":"API","bookFrom":"API","travelerType":1,"fleetId":"hoanglocal","fleetName":"Fleet Local","reservation":false,"pricingType":0,"currencyISO":"VND","currencySymbol":"đ","dispatch3rd":false,"request":{"pickUpTime":"Now","vehicleTypeRequest":"Bike","promo":"","rideSharing":false,"tip":3,"psgFleetId":"hoanglocal","serviceActive":true,"paymentType":2,"type":0,"hourly":0,"moreInfo":{"flightInfo":{"type":-1,"flightNumber":"","airline":""}},"operatorNote":"","note":"Auto test api","vehicleType":["Bike"],"destination":{"businessName":"","zipCode":"","geo":[108.266139,16.007381],"offset":"+07:00","timezone":"Asia/Saigon","address":"Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng"},"pickup":{"address":"Da Nang Software Park, Thạch Thang, Hải Châu, Đà Nẵng","zoneId":"5b278c85e4b02418de9de202","businessName":"","offset":"+07:00","timezone":"Asia/Saigon","zipCode":"","geo":[108.222198,16.075792]},"services":[],"typeRate":0},"bookingRideSharing":[],"dispatchRideSharing":false,"corporateInfo":{"division":"test","managerEmail":"test@gmail.com","corpId":"123","managerName":"","costCentre":"","department":"","corporateId":"5b3d86a2e4b0edd700de78d5","clientCaseMatter":"","chargeCode":"","name":"QUp"},"psgInfo":{"firstName":"Auto Test","lastName":"Demo 123","email":"tester.qup@gmail.com","phone":"+12063337779","fullName":"Auto Test Demo 123","creditInfo":{"cardMask":"XXXXXXXXXXXX4444","gateway":"Stripe"},"rank":0},"dispatchType":0}] |
        And I should have "Account" document in database with below info
            | total | specifiedInfo                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
            | 1     | {"fleetId": "hoanglocal", "phone": "+12063337779","registerFrom":"API", "firstName":"Auto Test","lastName":"Demo 123","email":"tester.qup@gmail.com", "corporateInfo.status" : 2, "corporateInfo.corpId" : "123", "corporateInfo.corpDivision" : "test", "corporateInfo.costCentre" : "", "corporateInfo.corpPO" : "", "corporateInfo.managerName" : "", "corporateInfo.managerEmail" : "test@gmail.com", "corporateInfo.title" : "", "corporateInfo.department" : "" } |


