Feature: Request Booking from API when customer is personal
    Everybody wants to know when customer is personal

    # Booking Form API lấy Tip default
    Scenario: 1. Request Booking by API with Booking type = 0 & "paymentType" = 1
        Given Get token when login Account 3rd from "local"
        When I request booking from API when custom data
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
            | { "psgInfo": { "phone": "+12058889999", "firstName": "Auto Test", "lastName": "Demo 123", "email": "tester.qup@gmail.com", "creditInfo": { "cardNumber": "5555555555554444", "cardHolder": "Auto", "postalCode": "98789", "expiredDate": "12/2022", "cvv": "123" } }, "request": { "pickup": { "address": "Da Nang Software Park, Thạch Thang, Hải Châu, Đà Nẵng", "geo": [108.222198, 16.075792], "timezone": "Asia/Saigon" }, "destination": { "address": "Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng", "geo": [108.266139, 16.007381], "timezone": "Asia/Saigon" }, "pickUpTime": "Now", "vehicleTypeRequest": "Bike", "type": 0, "paymentType": 1, "note": "Auto test api", "promo": "", "rideSharing": false, "tip": 10.99, "packageRateId": "5b3d8590e4b0edd700de78cf" }, "dispatch3rd": false, "corporateInfo": { "division": "", "managerEmail": "", "corpId": "", "managerName": "", "costCentre": "", "department": "", "corporateId": "", "clientCaseMatter": "", "chargeCode": "" } } |
        Then Booking create successful
        And I should have "Booking" document in database with "1" Booking ID

    Scenario: 2. Request Booking by API with Booking type = 0 & "paymentType" = 2
        Given Get token when login Account 3rd from "local"
        When I request booking from API when custom data
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
            | { "psgInfo": { "phone": "+12058889999", "firstName": "Auto Test", "lastName": "Demo 123", "email": "tester.qup@gmail.com", "creditInfo": { "cardNumber": "5555555555554444", "cardHolder": "Auto", "postalCode": "98789", "expiredDate": "12/2022", "cvv": "123" } }, "request": { "pickup": { "address": "Da Nang Software Park, Thạch Thang, Hải Châu, Đà Nẵng", "geo": [108.222198, 16.075792], "timezone": "Asia/Saigon" }, "destination": { "address": "Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng", "geo": [108.266139, 16.007381], "timezone": "Asia/Saigon" }, "pickUpTime": "Now", "vehicleTypeRequest": "Bike", "type": 0, "paymentType": 2, "note": "Auto test api", "promo": "", "rideSharing": false, "tip": 10.99, "packageRateId": "5b3d8590e4b0edd700de78cf" }, "dispatch3rd": false, "corporateInfo": { "division": "", "managerEmail": "", "corpId": "", "managerName": "", "costCentre": "", "department": "", "corporateId": "", "clientCaseMatter": "", "chargeCode": "" } } |
        Then Booking create successful
        And I should have "Booking" document in database with "1" Booking ID

    Scenario: 3. Request Booking by API with Booking type = 0 & "paymentType" = 5
        Given Get token when login Account 3rd from "local"
        When I request booking from API when custom data
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
            | { "psgInfo": { "phone": "+12058889999", "firstName": "Auto Test", "lastName": "Demo 123", "email": "tester.qup@gmail.com", "creditInfo": { "cardNumber": "5555555555554444", "cardHolder": "Auto", "postalCode": "98789", "expiredDate": "12/2022", "cvv": "123" } }, "request": { "pickup": { "address": "Da Nang Software Park, Thạch Thang, Hải Châu, Đà Nẵng", "geo": [108.222198, 16.075792], "timezone": "Asia/Saigon" }, "destination": { "address": "Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng", "geo": [108.266139, 16.007381], "timezone": "Asia/Saigon" }, "pickUpTime": "Now", "vehicleTypeRequest": "Bike", "type": 0, "paymentType": 5, "note": "Auto test api", "promo": "", "rideSharing": false, "tip": 10.99, "packageRateId": "5b3d8590e4b0edd700de78cf" }, "dispatch3rd": false, "corporateInfo": { "division": "", "managerEmail": "", "corpId": "", "managerName": "", "costCentre": "", "department": "", "corporateId": "", "clientCaseMatter": "", "chargeCode": "" } } |
        Then Booking create successful
        And I should have "Booking" document in database with "1" Booking ID

    Scenario: 4. Request Booking by API with Booking type = 0 & "paymentType" = 6
        Given Get token when login Account 3rd from "local"
        When I request booking from API when custom data
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
            | { "psgInfo": { "phone": "+12058889999", "firstName": "Auto Test", "lastName": "Demo 123", "email": "tester.qup@gmail.com", "creditInfo": { "cardNumber": "5555555555554444", "cardHolder": "Auto", "postalCode": "98789", "expiredDate": "12/2022", "cvv": "123" } }, "request": { "pickup": { "address": "Da Nang Software Park, Thạch Thang, Hải Châu, Đà Nẵng", "geo": [108.222198, 16.075792], "timezone": "Asia/Saigon" }, "destination": { "address": "Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng", "geo": [108.266139, 16.007381], "timezone": "Asia/Saigon" }, "pickUpTime": "Now", "vehicleTypeRequest": "Bike", "type": 0, "paymentType": 6, "note": "Auto test api", "promo": "", "rideSharing": false, "tip": 10.99, "packageRateId": "5b3d8590e4b0edd700de78cf" }, "dispatch3rd": false, "corporateInfo": { "division": "", "managerEmail": "", "corpId": "", "managerName": "", "costCentre": "", "department": "", "corporateId": "", "clientCaseMatter": "", "chargeCode": "" } } |
        Then Booking create successful
        And I should have "Booking" document in database with "1" Booking ID
        And I should have "Booking" document in database with below expected data
            | specifiedInfo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
            | [{"platform":"API","bookFrom":"API","travelerType":0,"fleetId":"hoanglocal","fleetName":"Fleet Local","reservation":false,"pricingType":0,"currencyISO":"VND","currencySymbol":"đ","dispatch3rd":false,"request":{"pickUpTime":"Now","vehicleTypeRequest":"Bike","psgFleetId":"hoanglocal","paymentType":2,"type":0,"hourly":0,"note":"Auto test api","vehicleType":["Bike"],"destination":{"businessName":"","zipCode":"","geo":[108.266139,16.007381],"offset":"+07:00","timezone":"Asia/Saigon","address":"Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng"},"pickup":{"address":"Da Nang Software Park, Thạch Thang, Hải Châu, Đà Nẵng","businessName":"","offset":"+07:00","timezone":"Asia/Saigon","zipCode":"","geo":[108.222198,16.075792]},"typeRate":0},"psgInfo":{"firstName":"Auto Test","lastName":"Demo 123","email":"tester.qup@gmail.com","phone":"+12058889999","fullName":"Auto Test Demo 123","creditInfo":{"cardMask":"XXXXXXXXXXXX4444","gateway":"Stripe"},"rank":0},"dispatchType":0}] |

    #Booking reservation  "pickUpTime": "2018-12-15 12:31"
    Scenario: 5. Request Booking by API with Booking type = 0 & "paymentType" = 1
        Given Get token when login Account 3rd from "local"
        When I request booking from API when custom data
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
            | { "psgInfo": { "phone": "+12058889999", "firstName": "Auto Test", "lastName": "Demo 123", "email": "tester.qup@gmail.com", "creditInfo": { "cardNumber": "5555555555554444", "cardHolder": "Auto", "postalCode": "98789", "expiredDate": "12/2022", "cvv": "123" } }, "request": { "pickup": { "address": "Da Nang Software Park, Thạch Thang, Hải Châu, Đà Nẵng", "geo": [108.222198, 16.075792], "timezone": "Asia/Saigon" }, "destination": { "address": "Vinpearl Luxury Da Nang, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng", "geo": [108.266139, 16.007381], "timezone": "Asia/Saigon" }, "pickUpTime": "2018-12-15 12:31", "vehicleTypeRequest": "Bike", "type": 0, "paymentType": 1, "note": "Auto test api", "promo": "", "rideSharing": false, "tip": 10.99, "packageRateId": "5b3d8590e4b0edd700de78cf" }, "dispatch3rd": false, "corporateInfo": { "division": "", "managerEmail": "", "corpId": "", "managerName": "", "costCentre": "", "department": "", "corporateId": "", "clientCaseMatter": "", "chargeCode": "" } } |
        Then Booking create successful
        And I should have "Booking" document in database with "1" Booking ID
