Feature: New CC Update Setting/ General
    Everybody wants update to Regular Rate

    Scenario: 01. I get data Setting/ Update General
        Given Get token when login Account NewCC from "Lab"
            | user     | password   |
            | tappcar1 | demo@12345 |
        When I send request to api "https://ccliteapis.lab.qup.vn/api/setting/general/save" with request with params based on table below
            | requestBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
            | {"fleetId":"tappcar","cancellationPolicy":{"onDemand":true,"duration":1,"times":3,"inAdvance":true,"durationIn":1,"durationInUnit":"hour"},"noShow":{"isActive":true,"applyCountDown":false,"countdownDuration":0},"airport":{"fromAirportActive":true,"fromAirport":0,"toAirportActive":true,"toAirport":0,"payTo":0,"fromAirportByCurrencies":[{"currencyISO":"USD","value":0},{"currencyISO":"CAD","value":10}],"toAirportByCurrencies":[{"currencyISO":"USD","value":0},{"currencyISO":"CAD","value":5}]},"meetDriver":{"onCurb":0,"meetDrv":0,"payTo":0,"meetDrvByCurrencies":[{"currencyISO":"USD","value":0},{"currencyISO":"CAD","value":5}],"onCurbByCurrencies":[{"currencyISO":"USD","value":0},{"currencyISO":"CAD","value":1}]},"additionalServicesActive":false,"rushHourActive":true,"otherFeeActive":true,"otherFee":{"value":0,"isEdit":true,"addNote":true,"valueByCurrencies":[{"currencyISO":"USD","value":10},{"currencyISO":"CAD","value":50}]},"taxActive":true,"tax":7,"tipActive":true,"tips":3,"tollFeeActive":true,"tollFeePayTo":0,"heavyTrafficActive":true,"heavyTrafficSurcharge":10,"heavyTrafficByCurrencies":[{"currencyISO":"USD","value":0}],"driverAppAlert":2,"driverAppAlertUnit":"hour","paxAppAlert":2,"paxAppAlertUnit":"hour","generalSetting":{"advanceInfoCorp":false,"soundNotify":false,"regAsCorpTraveler":false,"notAllowMakeBookingWithoutAssignFare":false,"disableInvoicingReceipt":false,"hideProviderFromCorp":false,"optionalEmailPaxApp":false,"disableHourlyRate":false,"genderRequireInPaxApp":false},"statusOnMap":["bookIn","offered","booked","arrived","engaged","droppedOff","action","bookOff"],"SOSNumber":{"defaultNumber":"","zoneNumber":[{"zoneId":"580ee1bee4b0c367990754b2","phone":""},{"zoneId":"580ee1e1e4b0c367990754b3","phone":""},{"zoneId":"585b93eae4b04955025fdd44","phone":""},{"zoneId":"5968518ce4b086a95f6bf67e","phone":""},{"zoneId":"5ae43521e4b0e7732133a9f9","phone":""}]}} |
        Then I should get the return data matches with
            | res                                                                                 |
            | { "fare": {"_id":"580ee145e4b0c3679907548e", "fleetId":"tappcar", "isActive":true}} |


